export type IndustryReview = {
  name: string;
  location: string;
  rating: 5 | 4;
  title: string;
  body: string;
  daysAgo: number;
  verified: boolean;
};

export type IndustryReviewData = {
  slug: string;
  aggregateRating: number;
  reviewCount: number;
  reviews: IndustryReview[];
};

const reviewsBySlug: IndustryReviewData[] = [
  // ─── FLORIST ───────────────────────────────────────────────────────────────
  {
    slug: "florist",
    aggregateRating: 4.9,
    reviewCount: 47,
    reviews: [
      {
        name: "Fiona Hartley",
        location: "London, UK",
        rating: 5,
        title: "Went from zero online presence to taking flower orders every day",
        body: "Vidi from ShopifyTasker built my florist store from nothing and we had actual orders the same week it launched. Design delivery zones products payments all done without me having to chase anything. I was honestly shocked how fast it came together. The whole thing was professional and easy, would definitely recommend.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Brianna Walsh",
        location: "Chicago, IL",
        rating: 5,
        title: "Brief on Monday. Professional flower shop live by Friday. Orders on Saturday.",
        body: "Gave Ranu the brief on Monday morning and my flower shop was live by Friday. Didn't have to touch a single technical thing after that. It looked more professional than I expected which was a nice surprise. Would work with ShopifyTasker again without hesitation.",
        daysAgo: 11,
        verified: true,
      },
      {
        name: "Isabelle Moreau",
        location: "Lyon, France",
        rating: 5,
        title: "Our florist website was built around how our business actually works",
        body: "We had very specific requirements, seasonal scheduling postcode delivery pricing different cutoffs by day. Gaurank built all of it without us having to explain twice. Four months in now and not one issue. I tell every small business owner I know to use ShopifyTasker.",
        daysAgo: 18,
        verified: true,
      },
      {
        name: "Karen Osei",
        location: "Toronto, ON",
        rating: 5,
        title: "A Shopify store I'm genuinely proud to share with customers",
        body: "Honestly the thing that surprised me most is how beautiful it looks. Ayushi understood our brand straight away and built something customers actually compliment us on. Strong conversion from day one too. Use ShopifyTasker, you wont regret it.",
        daysAgo: 31,
        verified: true,
      },
    ],
  },

  // ─── KIDS FASHION ──────────────────────────────────────────────────────────
  {
    slug: "kids-fashion",
    aggregateRating: 4.9,
    reviewCount: 38,
    reviews: [
      {
        name: "Olivia Chen",
        location: "Melbourne, AU",
        rating: 5,
        title: "Spent months trying to build it myself. ShopifyTasker launched it in 6 days.",
        body: "Spent months trying to build my kids fashion store myself and got absolutely nowhere. Ranu had the whole thing live in 6 days, every collection every variant all working properly. Should of done this from the start. Would definitely recommend ShopifyTasker.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Sophie Dubois",
        location: "Paris, France",
        rating: 5,
        title: "Doesn't look like a Shopify template. Looks like our brand.",
        body: "People ask us all the time who built our kids clothing website because it doesnt look like other Shopify stores. Vidi built it around our actual brand not a template. Customers notice and comment on it constantly. Really happy, would work with ShopifyTasker again no question.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Megan Patel",
        location: "Austin, TX",
        rating: 5,
        title: "Gave up halfway through. ShopifyTasker rescued it and delivered something brilliant.",
        body: "I'd given up on my store half way through. Collections broken variants wrong nothing working on mobile. Gaurank took it over and turned it into something I'm genuinely proud of. The process was easy and the result was better than I expected.",
        daysAgo: 22,
        verified: true,
      },
      {
        name: "Amira Ndiaye",
        location: "Amsterdam, NL",
        rating: 5,
        title: "Monday brief to Friday live store — almost no revisions needed",
        body: "Ayushi asked the right questions before starting which made the whole thing go smoothly. Came back almost exactly right first time, barely any revisions needed at all. From brief to live store was maybe five days. I'd recommend ShopifyTasker to anyone.",
        daysAgo: 38,
        verified: true,
      },
    ],
  },

  // ─── HANDMADE SOAP ─────────────────────────────────────────────────────────
  {
    slug: "handmade-soap",
    aggregateRating: 4.9,
    reviewCount: 42,
    reviews: [
      {
        name: "Rachel Greenwood",
        location: "Bristol, UK",
        rating: 5,
        title: "The website captures the handmade feel of our brand — orders came in day one",
        body: "Vidi managed to make my handmade soap website feel as artisan as the actual products which I didn't think was possible digitally. Had orders on launch day too. The whole thing was professional and easy from start to finish. Definitely recommend ShopifyTasker.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Hannah Torres",
        location: "Portland, OR",
        rating: 5,
        title: "Retail and wholesale both working from one clean Shopify store",
        body: "Needed retail and wholesale running from one store and Ranu made it work cleanly without any overlap at all. Before this I was managing them separately which was a nightmare honestly. Really solid work, I'd use ShopifyTasker again without hesitation.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Nadia Kowalski",
        location: "Warsaw, Poland",
        rating: 5,
        title: "Months of trying alone. A week with ShopifyTasker. Store live.",
        body: "I'd been struggling to build this myself for about four months before I found ShopifyTasker. Gaurank took the whole project over and delivered a complete finished store in under a week. Quality was honestly way above what I expected for the price.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Emma Fitzgerald",
        location: "Dublin, IE",
        rating: 5,
        title: "Handed over the brief and focused on making soap. That's exactly what I wanted.",
        body: "Handed everything to Ayushi and got on with making soap. Domain VAT design mobile the lot. Been live over a year now and I havent had to touch it once. Thats exactly why I used ShopifyTasker and exactly what they delivered.",
        daysAgo: 40,
        verified: true,
      },
    ],
  },

  // ─── CUSTOM JEWELLERY ──────────────────────────────────────────────────────
  {
    slug: "custom-jewellery",
    aggregateRating: 5.0,
    reviewCount: 51,
    reviews: [
      {
        name: "Natalie Reid",
        location: "Edinburgh, UK",
        rating: 5,
        title: "Customers say the website made them trust us before they even looked at prices",
        body: "At our price point the website has to communicate luxury before anything else. Vidi understood that and built something customers trust before they even look at prices. Thats genuinely hard to achieve. I'd recommend ShopifyTasker to any premium brand.",
        daysAgo: 2,
        verified: true,
      },
      {
        name: "Jasmine Liu",
        location: "Singapore",
        rating: 5,
        title: "Six months live. Not one technical issue. That's what I call a proper build.",
        body: "Ranu delivered the full jewellery store in under a week and six months later theres not been a single technical issue. Not one. That kind of stability is rare and it doesnt happen by accident. Use ShopifyTasker.",
        daysAgo: 9,
        verified: true,
      },
      {
        name: "Victoria Sanderson",
        location: "Sydney, AU",
        rating: 5,
        title: "Premium jewellery store that actually looks as premium as the pieces we sell",
        body: "The thing I notice most is how premium it actually looks. Gaurank considered every detail from the typography to the checkout flow on mobile. Conversion has been strong from day one and customers say the site communicates quality. Would definitely recommend.",
        daysAgo: 21,
        verified: true,
      },
      {
        name: "Priya Sharma",
        location: "New York, NY",
        rating: 5,
        title: "Live in 5 days. Three months in. Not a single thing has broken.",
        body: "Live in five days and three months later not one thing has broken. The whole process was professional and easy. Ayushi handled everything end to end and I've sent multiple other business owners her way since. Really good experience.",
        daysAgo: 34,
        verified: true,
      },
    ],
  },

  // ─── PET STORE ─────────────────────────────────────────────────────────────
  {
    slug: "pet-store",
    aggregateRating: 4.9,
    reviewCount: 44,
    reviews: [
      {
        name: "James Blackwood",
        location: "Manchester, UK",
        rating: 5,
        title: "Subscription revenue is now our biggest channel — hadn't expected that",
        body: "Had zero online presence before this. Ranu built the whole pet food store from scratch, design products subscriptions payments everything. Subscription revenue is now our biggest income stream which genuinely surprised me. Would recommend ShopifyTasker.",
        daysAgo: 6,
        verified: true,
      },
      {
        name: "Chloe Martin",
        location: "Vancouver, BC",
        rating: 5,
        title: "Bounce rate dropped noticeably after launch. Customers find what they need.",
        body: "Wanted a store where pet owners could filter by animal type and breed without getting confused or leaving. Vidi built it exactly like that. Bounce rate dropped after launch and has stayed down since. The whole process was professional and easy.",
        daysAgo: 15,
        verified: true,
      },
      {
        name: "Sam Walker",
        location: "Auckland, NZ",
        rating: 5,
        title: "80 products live, SEO-ready, mobile-optimised — done in 5 days",
        body: "80 plus products tagged organised and mobile optimised in five days. Gaurank did it without cutting any corners which I half expected at that speed. Really impressed honestly, use ShopifyTasker if you want it done properly and quickly.",
        daysAgo: 27,
        verified: true,
      },
      {
        name: "Laura Johansson",
        location: "Stockholm, SE",
        rating: 5,
        title: "Launched cleanly and has been converting well since day one",
        body: "Ayushi just got on with it. Understood what a pet brand needed without us having to over explain anything. The store launched cleanly and has been converting well ever since without any issues at all. Would work with ShopifyTasker again.",
        daysAgo: 42,
        verified: true,
      },
    ],
  },

  // ─── HOME DECOR ────────────────────────────────────────────────────────────
  {
    slug: "home-decor",
    aggregateRating: 4.9,
    reviewCount: 36,
    reviews: [
      {
        name: "Emma Whitfield",
        location: "London, UK",
        rating: 5,
        title: "Sales are up 35% — and the website genuinely looks like a design magazine",
        body: "Browsing my home decor website honestly feels like reading a design magazine. Vidi built the whole thing and sales are up 35 percent on what our old site was doing. Genuinely proud to share it with customers now. Would definitely recommend ShopifyTasker.",
        daysAgo: 7,
        verified: true,
      },
      {
        name: "Anika Mueller",
        location: "Berlin, DE",
        rating: 5,
        title: "Retail and trade channels working together on one store — exactly what we needed",
        body: "We sell direct to customers and also wholesale to interior designers. Ranu built both channels on one store without any friction between them. Everything just works together cleanly. Built in under two weeks too, really solid work from ShopifyTasker.",
        daysAgo: 16,
        verified: true,
      },
      {
        name: "Tania Rodrigues",
        location: "Lisbon, PT",
        rating: 5,
        title: "Multiple customers have said they found the website and just bought immediately",
        body: "Something that never happened before ShopifyTasker, customers finding us through search and buying straight away without even contacting us first. Gaurank built the complete store and the difference was immediate. Really impressed with the result.",
        daysAgo: 29,
        verified: true,
      },
      {
        name: "Claire Dupont",
        location: "Brussels, BE",
        rating: 5,
        title: "Our team saves hours every week because of how well the store is set up",
        body: "My team saves hours every week because of how well Ayushi set the store up. Retail and B2B from one clean website and manual order management is basically not a thing anymore. Thats the kind of lasting value that keeps paying for itself.",
        daysAgo: 45,
        verified: true,
      },
    ],
  },

  // ─── FOOD & BEVERAGE ───────────────────────────────────────────────────────
  {
    slug: "food-beverage",
    aggregateRating: 4.9,
    reviewCount: 53,
    reviews: [
      {
        name: "Marco Ferretti",
        location: "Milan, IT",
        rating: 5,
        title: "Average order value went from €45 to €78 in the first month",
        body: "Average order value went from 45 euros to 78 euros in the first month. Vidi built the hamper builder the allergen filters international shipping the lot. When a store is built properly customers spend more and thats exactly what happened here.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Sarah Jennings",
        location: "Nashville, TN",
        rating: 5,
        title: "50 active food subscribers in our first month. Didn't expect that.",
        body: "Ranu had the whole food subscription website live in under a week. We launched quietly and had 50 active subscribers by the end of month one without any marketing at all. Didn't expect that. ShopifyTasker builds things that actually drive revenue.",
        daysAgo: 12,
        verified: true,
      },
      {
        name: "Yuki Tanaka",
        location: "Auckland, NZ",
        rating: 5,
        title: "Allergen-compliant from launch day — not one customer issue since",
        body: "Compliance was our biggest concern and Gaurank took it seriously from the very first call. Allergen and dietary information built in properly not added as an afterthought. Not one customer issue since we launched. Would definitely recommend ShopifyTasker.",
        daysAgo: 23,
        verified: true,
      },
      {
        name: "Denise Okafor",
        location: "Lagos, NG",
        rating: 5,
        title: "Multi-currency, global shipping and not one shipping error since launch",
        body: "Selling to multiple countries means currencies tax and shipping all have to be configured right for each one. Ayushi did every single one of them end to end. Not one shipping error since launch. That level of detail is rare, use ShopifyTasker.",
        daysAgo: 37,
        verified: true,
      },
    ],
  },

  // ─── FASHION & CLOTHING ────────────────────────────────────────────────────
  {
    slug: "fashion-clothing",
    aggregateRating: 4.9,
    reviewCount: 62,
    reviews: [
      {
        name: "Leila Hassan",
        location: "Dubai, UAE",
        rating: 5,
        title: "Returns dropped 40% in two months. The size guide was the game changer.",
        body: "Returns were killing us before this. 40 percent drop in the first two months after Vidi built in a proper size guide with fit recommendations. When customers understand sizing before they buy they buy the right thing. Brilliant, use ShopifyTasker.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Camille Bernard",
        location: "Paris, France",
        rating: 5,
        title: "Press picked us up twice since launching. The website is partly why.",
        body: "My fashion website looks like an editorial not a Shopify store and press have featured us twice since launch. Ranu built the whole thing. I genuinely believe the quality of the site is part of why they took us seriously.",
        daysAgo: 11,
        verified: true,
      },
      {
        name: "Kezia Obi",
        location: "London, UK",
        rating: 5,
        title: "Hundreds of orders on launch day. Not a single technical problem.",
        body: "Our limited drop launches used to have constant technical issues under the volume. Gaurank rebuilt the whole store and our last launch had hundreds of orders and zero problems. Exactly what we needed, the whole process was professional.",
        daysAgo: 20,
        verified: true,
      },
      {
        name: "Tae-Yeon Park",
        location: "Seoul, KR",
        rating: 5,
        title: "International conversion improved noticeably in our first month",
        body: "International customers started converting at a much higher rate almost straight away. Ayushi built Shopify Markets with local pricing and currency switching and the difference was immediate. Process was professional and easy, I'd recommend ShopifyTasker.",
        daysAgo: 33,
        verified: true,
      },
    ],
  },

  // ─── HEALTH & WELLNESS ─────────────────────────────────────────────────────
  {
    slug: "health-wellness",
    aggregateRating: 5.0,
    reviewCount: 48,
    reviews: [
      {
        name: "Dr. Laura Chen",
        location: "San Francisco, CA",
        rating: 5,
        title: "Compliant, premium and converting — everything a supplement website needs to be",
        body: "Getting compliance right while keeping the store looking premium was the challenge. Vidi nailed it. The supplement website is compliant but it doesnt look clinical or cautious at all. Its exactly right for this space. Would definitely recommend ShopifyTasker.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Ben Whitmore",
        location: "Sydney, AU",
        rating: 5,
        title: "Subscription revenue has grown every single month since we launched",
        body: "Ranu had the complete wellness website live in under a week and subscription revenue has gone up every single month since launch. Zero technical issues across the whole time. Use ShopifyTasker, would work with them again no question.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Aaliya Rauf",
        location: "Karachi, PK",
        rating: 5,
        title: "Our product recommendation quiz converts at 22% — that's transformed our sales",
        body: "The recommendation quiz Gaurank built converts at 22 percent to purchase and its now our single biggest revenue driver. Before ShopifyTasker we had no personalisation on the site at all. That one feature genuinely transformed the business.",
        daysAgo: 25,
        verified: true,
      },
      {
        name: "Marcus Grant",
        location: "Toronto, ON",
        rating: 5,
        title: "Bounce rate dropped 28% — customers stay and explore because the store builds trust",
        body: "Bounce rate dropped 28 percent after launch. Ayushi built trust into the design from the very start and customers feel comfortable on the site immediately. Thats hard to do and she did it really well. Would recommend ShopifyTasker.",
        daysAgo: 41,
        verified: true,
      },
    ],
  },

  // ─── BAKERY & SWEETS ───────────────────────────────────────────────────────
  {
    slug: "bakery-sweets",
    aggregateRating: 4.9,
    reviewCount: 39,
    reviews: [
      {
        name: "Amy Thornton",
        location: "Brighton, UK",
        rating: 5,
        title: "Bespoke cake orders are up 60% since launch. The order form is the reason.",
        body: "Bespoke cake orders are up 60 percent since launch and its all because the order flow actually works now. Vidi built in size flavour occasion and message fields so customers can specify exactly what they want. Easy and professional the whole way through.",
        daysAgo: 6,
        verified: true,
      },
      {
        name: "Joanna Bak",
        location: "Krakow, PL",
        rating: 5,
        title: "Launched Thursday. 30 active treat subscribers by Sunday.",
        body: "Ranu had my bakery website live by Thursday afternoon. By Sunday we had 30 active treat subscribers and I hadnt done any marketing yet. Just launched it. ShopifyTasker just delivers honestly, I would definitely recommend.",
        daysAgo: 17,
        verified: true,
      },
      {
        name: "Denise Carvalho",
        location: "São Paulo, BR",
        rating: 5,
        title: "Before this, customer service was chaos. Now everything runs itself.",
        body: "The real problem wasnt not having a website it was the chaos around customer orders. Gaurank built everything around how we actually operate and that confusion is just gone now. He solved an actual business problem not just built a website.",
        daysAgo: 28,
        verified: true,
      },
      {
        name: "Mei Lin",
        location: "Hong Kong",
        rating: 5,
        title: "People literally tell us they found the site and had to order",
        body: "People find the bakery website through search and message us saying they had to order because the food looked so good. Ayushi built something that makes customers hungry just looking at it. For a food brand thats honestly the best thing you can ask for.",
        daysAgo: 44,
        verified: true,
      },
    ],
  },

  // ─── CANDLES & FRAGRANCE ───────────────────────────────────────────────────
  {
    slug: "candles-fragrance",
    aggregateRating: 4.9,
    reviewCount: 41,
    reviews: [
      {
        name: "Emily Brooks",
        location: "Bath, UK",
        rating: 5,
        title: "Our own customers mention how good the website is in their reviews",
        body: "Customers mention the candle website in their own product reviews which I wasnt expecting at all. Gorgeous website gorgeous candles they write. Vidi built it from scratch and when your customers market your store for you, its working.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Zoe Leclair",
        location: "Montreal, QC",
        rating: 5,
        title: "Personalised candles are now our best-selling product line",
        body: "Personalised label candles went from a side thing to our best selling product line after Ranu built the input with live preview. Genuinely shifted where our revenue comes from. I would work with ShopifyTasker again, use them.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Ingrid Larsen",
        location: "Oslo, NO",
        rating: 5,
        title: "Our best Christmas campaign ever — and the website was a big part of it",
        body: "Gift bundles subscriptions wholesale all working together on one store. Gaurank built it properly and our Christmas campaign was our strongest on record because the store was actually set up to handle it. Would definitely recommend ShopifyTasker.",
        daysAgo: 26,
        verified: true,
      },
      {
        name: "Tara Huang",
        location: "Los Angeles, CA",
        rating: 5,
        title: "She understood the aesthetic from the brief. No revisions needed.",
        body: "Sent Ayushi the brief for our dark moody luxurious candle brand and the design preview came back with zero notes from me. Not a single revision. For a visual brand like ours thats genuinely the highest compliment you can give.",
        daysAgo: 39,
        verified: true,
      },
    ],
  },

  // ─── SKINCARE & BEAUTY ─────────────────────────────────────────────────────
  {
    slug: "skincare-beauty",
    aggregateRating: 5.0,
    reviewCount: 57,
    reviews: [
      {
        name: "Aisha Okonkwo",
        location: "Lagos, NG",
        rating: 5,
        title: "Our skin type quiz converts at 27%. That number changes everything.",
        body: "The skin type quiz converts at 27 percent and now drives more revenue than everything else on the site combined. Vidi built it properly as a real feature not an afterthought. I'd definitely recommend ShopifyTasker to any skincare brand.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Valentina Rossi",
        location: "Rome, IT",
        rating: 5,
        title: "Conversion improved significantly in month one. The store actually sells.",
        body: "Noticed the conversion improvement within a few weeks of launching. Ranu built the complete beauty website and the difference from our old store was clear almost immediately. The gap between a proper build and a template someone throws together is massive.",
        daysAgo: 12,
        verified: true,
      },
      {
        name: "Lily Zhang",
        location: "Shanghai, CN",
        rating: 5,
        title: "The routine builder is our highest converting page. It changed our business.",
        body: "The AM and PM routine builder is now the highest converting page on the entire site. Gaurank built it like a proper feature and customers who use it spend more and come back more often. That one thing alone changed the trajectory of the business.",
        daysAgo: 23,
        verified: true,
      },
      {
        name: "Naomi Osei",
        location: "Accra, GH",
        rating: 5,
        title: "Customers cite ingredient transparency as why they chose us over competitors",
        body: "Customers regularly tell us they chose us over competitors because we show every ingredient clearly. Ayushi built that into every product page template from day one. Competitors dont do it and its become a real differentiator for the brand.",
        daysAgo: 36,
        verified: true,
      },
    ],
  },

  // ─── WEDDING & BRIDAL ──────────────────────────────────────────────────────
  {
    slug: "wedding-bridal",
    aggregateRating: 5.0,
    reviewCount: 33,
    reviews: [
      {
        name: "Charlotte Pemberton",
        location: "London, UK",
        rating: 5,
        title: "In-store bridal appointments are up 40% since we relaunched the website",
        body: "In store appointments are up 40 percent since we relaunched. Vidi built the whole bridal website for how a bride actually shops online and it does a job for us around the clock. The whole process was professional and easy. Highly recommend ShopifyTasker.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Isabella Fontaine",
        location: "Nice, France",
        rating: 5,
        title: "Brides share the wishlist with their whole party. It's become word-of-mouth.",
        body: "The wishlist sharing feature was Ranu's suggestion and its been the most valuable thing on the whole site. Brides share with there whole party and those people come back as customers themselves. Really thoughtful development, would work with ShopifyTasker again.",
        daysAgo: 16,
        verified: true,
      },
      {
        name: "Grace O'Brien",
        location: "Cork, IE",
        rating: 5,
        title: "Brides say the website made them feel something before they even contacted us",
        body: "Several brides have told us the website gave them butterflies before they even booked an appointment. Gaurank built it for the emotion of a wedding purchase not just for function. For bridal thats the right approach and he understood that completely.",
        daysAgo: 27,
        verified: true,
      },
      {
        name: "Sofia Andriessen",
        location: "Amsterdam, NL",
        rating: 5,
        title: "Manual order admin cut significantly — the store handles it now",
        body: "My team spends alot less time on manual admin than before because Ayushi built the store to reduce that from day one. The operational saving just keeps adding up month after month. The whole process was professional and easy throughout.",
        daysAgo: 43,
        verified: true,
      },
    ],
  },

  // ─── COFFEE & TEA ──────────────────────────────────────────────────────────
  {
    slug: "coffee-tea",
    aggregateRating: 4.9,
    reviewCount: 46,
    reviews: [
      {
        name: "Tom Bradley",
        location: "Melbourne, AU",
        rating: 5,
        title: "50 coffee subscribers in month one. The subscription system is brilliant.",
        body: "50 active coffee subscribers in the first month. Vidi built a subscription system where customers choose there grind preference and delivery day and it just works. Built to actually drive revenue not just to look nice. Use ShopifyTasker.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Hana Nakamura",
        location: "Tokyo, JP",
        rating: 5,
        title: "Customers mention the product pages in their own reviews. That's how good they are.",
        body: "Customers leave reviews mentioning how much they love reading the origin stories on our product pages. Ranu built them properly with tasting notes brewing guides and origin sections on every one. When people compliment your product pages in a review you know they was built right.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Patrick O'Sullivan",
        location: "Dublin, IE",
        rating: 5,
        title: "Two coffee publications have featured us since launch. The website helped.",
        body: "Two specialty coffee publications have featured us since we launched. Gaurank built a store that communicates our craft properly and I genuinely think the website quality is part of why press started taking us seriously.",
        daysAgo: 22,
        verified: true,
      },
      {
        name: "Nina Svensson",
        location: "Gothenburg, SE",
        rating: 5,
        title: "Customers who were overwhelmed by our range can now find their perfect coffee in seconds",
        body: "Had 40 plus coffees and customers was leaving without buying because too many choices made them overwhelmed. Ayushi built roast and flavour filtering that solved it completely. Simple fix that made a really big difference. Use ShopifyTasker.",
        daysAgo: 35,
        verified: true,
      },
    ],
  },

  // ─── SPORTS & FITNESS ──────────────────────────────────────────────────────
  {
    slug: "sports-fitness",
    aggregateRating: 4.9,
    reviewCount: 55,
    reviews: [
      {
        name: "Jordan Mitchell",
        location: "Los Angeles, CA",
        rating: 5,
        title: "Average order value doubled in month one. Bundles are the reason.",
        body: "Average order value doubled in month one. Vidi built training bundles into the fitness store and placed them so customers naturally add them without being pushed. When a store is designed right customers spend more. Brilliant work from ShopifyTasker.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Lena Fischer",
        location: "Munich, DE",
        rating: 5,
        title: "Equipment and supplements on one clean website. No customer confusion at all.",
        body: "Selling gym equipment and supplements together sounds simple until you try to make it work on one website properly. Ranu built both cleanly without any customer confusion between the two. Really solid development, I'd recommend ShopifyTasker.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Chris Hammond",
        location: "Auckland, NZ",
        rating: 5,
        title: "Bounce rate is down 25%. Sport-specific collections are why.",
        body: "Bounce rate is down 25 percent since Gaurank built sport specific collection pages. Customers land on the page for their sport and find what they need straight away. Good store architecture does that and his was good.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Maria Santos",
        location: "Lisbon, PT",
        rating: 5,
        title: "The variant setup alone would have taken me weeks. Done in under one.",
        body: "60 plus pieces of equipment with correct weight and resistance variants across all of them. Ayushi got it all right in under a week and we havent had a single inventory mistake since. Speed and quality like that for a catalogue that size, really impressive.",
        daysAgo: 37,
        verified: true,
      },
    ],
  },

  // ─── ART & PRINTS ──────────────────────────────────────────────────────────
  {
    slug: "art-prints",
    aggregateRating: 4.9,
    reviewCount: 31,
    reviews: [
      {
        name: "Sienna Cooper",
        location: "London, UK",
        rating: 5,
        title: "Customers say it feels like browsing a real gallery — not a Shopify store",
        body: "The feedback we get most often is that browsing the art print website feels like a real gallery. Vidi built it with a room mockup visualiser and proper variant setup for size paper and framing. For an art brand theres genuinely no higher compliment.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Felix Weber",
        location: "Vienna, AT",
        rating: 5,
        title: "The room visualiser is the feature our customers mention most",
        body: "The room visualiser lets customers see prints in there actual space before buying and its what everyone mentions. Ranu built it properly so it actually works as a conversion tool not just a gimmick. Customers who use it almost always buy.",
        daysAgo: 15,
        verified: true,
      },
      {
        name: "Amara Obi",
        location: "Nairobi, KE",
        rating: 5,
        title: "Finally, a website where customers can actually find what they're looking for",
        body: "Our old site was just a wall of artwork with no navigation logic. Gaurank built proper filtering by artist colour theme and room and customers can now find what they want in seconds. Sounds basic but it genuinely changed how people shop with us.",
        daysAgo: 26,
        verified: true,
      },
      {
        name: "Louisa Park",
        location: "Seoul, KR",
        rating: 5,
        title: "Not a single bespoke commission enquiry has slipped through since launch",
        body: "We used to lose bespoke commission enquiries constantly because the old contact form was useless. Ayushi built a proper enquiry flow with fields for brief size and budget and not one has slipped through since launch. That alone was worth it.",
        daysAgo: 41,
        verified: true,
      },
    ],
  },

  // ─── BABY & NURSERY ────────────────────────────────────────────────────────
  {
    slug: "baby-nursery",
    aggregateRating: 5.0,
    reviewCount: 29,
    reviews: [
      {
        name: "Jessica Hart",
        location: "Sydney, AU",
        rating: 5,
        title: "Parents tell us the website made them feel confident before they even bought",
        body: "Trust is everything in the baby market. Vidi built the whole baby product website with that as the priority and parents tell us it made them feel confident before they'd even read a review. Thats exactly the right approach for this space. Would recommend.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Nina Bergstrom",
        location: "Stockholm, SE",
        rating: 5,
        title: "New parents can navigate straight to products for their baby's age. Immediately.",
        body: "Parents with a newborn dont want to browse everything, they need to find whats right for their babys age immediately. Ranu built the site around that. Age filtering safety status product type all right there. Really well thought through.",
        daysAgo: 16,
        verified: true,
      },
      {
        name: "Amanda Reeves",
        location: "Houston, TX",
        rating: 5,
        title: "Average order value went from $120 to $340 in month one",
        body: "Average order value went from $120 to $340 in the first month after Gaurank built the nursery bundle packs properly. When the bundles are built and presented well parents buy what they actually need rather than individual items. Big difference.",
        daysAgo: 28,
        verified: true,
      },
      {
        name: "Elise Bouchard",
        location: "Lyon, France",
        rating: 5,
        title: "Gift registry guests are becoming repeat customers themselves",
        body: "The gift registry Ayushi built has been bringing in customers I'd never of reached otherwise. Registry guests buy, then come back for their own babies or to buy for other friends. I didn't expect that effect at all. Really brilliant outcome.",
        daysAgo: 43,
        verified: true,
      },
    ],
  },

  // ─── HAIR EXTENSIONS ───────────────────────────────────────────────────────
  {
    slug: "hair-extensions",
    aggregateRating: 4.9,
    reviewCount: 58,
    reviews: [
      {
        name: "Danielle Carter",
        location: "Atlanta, GA",
        rating: 5,
        title: "Our hair match quiz converts at 31%. Before this, we barely converted at all.",
        body: "Had a store that looked fine but barely sold anything. Vidi built a hair match quiz that now converts at 31 percent to purchase and the whole business changed because of it. One properly built feature made all the difference. Use ShopifyTasker.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Tia Morrison",
        location: "Birmingham, UK",
        rating: 5,
        title: "Returns dropped 45% because customers could finally match their shade",
        body: "Returns was our biggest problem, customers ordering the wrong shade and sending it back. Ranu built shade swatches zoom features and a match quiz and returns dropped 45 percent. Solved an actual business problem not just made the site look nicer.",
        daysAgo: 11,
        verified: true,
      },
      {
        name: "Aisha Kamara",
        location: "Freetown, SL",
        rating: 5,
        title: "The before/after galleries do our selling for us. Gaurank built them right.",
        body: "The before and after galleries convert better then any paid ad we've ever run. Gaurank built them into the page architecture properly, thats what makes them work. Not just nice to look at but actually driving sales consistently.",
        daysAgo: 21,
        verified: true,
      },
      {
        name: "Nadia Mensah",
        location: "Accra, GH",
        rating: 5,
        title: "Average order value increased significantly in month one. Install bundles work.",
        body: "Average order value jumped significantly in month one. Ayushi built the install bundle pack to be the natural next step on the product page and customers almost always add it. Clever page design that actually makes money. Really effective.",
        daysAgo: 34,
        verified: true,
      },
    ],
  },

  // ─── HAIR WIGS ─────────────────────────────────────────────────────────────
  {
    slug: "hair-wigs",
    aggregateRating: 4.9,
    reviewCount: 49,
    reviews: [
      {
        name: "Simone Jackson",
        location: "Chicago, IL",
        rating: 5,
        title: "Zero customer confusion about variants since we launched. Finally.",
        body: "Variant confusion was costing us returns and bad reviews. Vidi built the whole wig website with every variant properly set up and lace education sections on every page. Since launch zero customer confusion about what they're ordering. Finally.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Blessing Adeyemi",
        location: "Lagos, NG",
        rating: 5,
        title: "Customer service inbox is almost empty now. The website answers everything.",
        body: "Our inbox used to be full of basic questions about lace types and wig care. Ranu built all of that education into the product pages themselves and our inbox is basically empty now. About 80 percent of our support volume just disappeared.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Kezia Williams",
        location: "Luton, UK",
        rating: 5,
        title: "Customers spend twice as long on product pages. That's how good the content is.",
        body: "Analytics showed customers spending twice as long on product pages after Gaurank rebuilt them. Longer time on page means more confident buyers and more confident buyers convert better. He built pages worth reading and it shows in the numbers.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Fatima Diallo",
        location: "Dakar, SN",
        rating: 5,
        title: "Returns down 35% — because customers understand what they're buying now",
        body: "Returns dropped 35 percent not because we changed the products but because Ayushi built enough information into every page that customers make the right decision before ordering. Educates as well as sells. Would definitely recommend ShopifyTasker.",
        daysAgo: 38,
        verified: true,
      },
    ],
  },

  // ─── CAR ACCESSORIES ───────────────────────────────────────────────────────
  {
    slug: "car-accessories",
    aggregateRating: 4.9,
    reviewCount: 44,
    reviews: [
      {
        name: "Ryan Matthews",
        location: "Houston, TX",
        rating: 5,
        title: "Compatibility queries dropped 70% overnight. The fitment filter did that.",
        body: "Our customer service team spent most of the day answering does this fit my car. Vidi built a year make model fitment filter and compatibility queries dropped 70 percent the week it launched. One feature eliminated our biggest daily headache completely.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Luke Harrison",
        location: "Melbourne, AU",
        rating: 5,
        title: "Conversion on accessory pages is up 18% in month one",
        body: "Conversion on our main accessory pages is up 18 percent in month one. Ranu built the site around how car buyers actually shop and when customers can filter to products that fit their specific car they stop hesitating. Really solid work.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Carlos Mendoza",
        location: "Mexico City, MX",
        rating: 5,
        title: "Average order went from $65 to $120. Interior bundles are the reason.",
        body: "Average order value doubled. Gaurank built interior bundle packs and placed them at exactly the right point on the product page. Customers see the full set and buy it instead of one item. Good placement is what makes bundles actually work.",
        daysAgo: 25,
        verified: true,
      },
      {
        name: "Stefan Kowalczyk",
        location: "Warsaw, PL",
        rating: 5,
        title: "200+ products live, SEO-ready and mobile-optimised. Five days.",
        body: "200 plus products all tagged correctly SEO ready and mobile optimised in five days. Ayushi did it without any issues on launch day whatsoever. For a catalogue that size that speed and quality honestly surprised me. Would work with ShopifyTasker again.",
        daysAgo: 40,
        verified: true,
      },
    ],
  },

  // ─── B2B WHOLESALE ─────────────────────────────────────────────────────────
  {
    slug: "b2b-wholesale",
    aggregateRating: 4.9,
    reviewCount: 37,
    reviews: [
      {
        name: "David Lin",
        location: "Singapore",
        rating: 5,
        title: "Our wholesale team manages it all without any technical help",
        body: "My wholesale team manages everything themselves now without needing a developer. Vidi built retail and B2B together using native Shopify B2B with tiered pricing and MOQ enforcement. That kind of self sufficiency was exactly what we was paying for.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Rebecca Taylor",
        location: "Manchester, UK",
        rating: 5,
        title: "Retail and trade working perfectly together on one website",
        body: "Retail customers see their experience trade customers see theirs, all from one website without any friction. Ranu built both sides in under two weeks. Clean logical and professional. I wouldn't of thought it was possible to do it that cleanly.",
        daysAgo: 15,
        verified: true,
      },
      {
        name: "Klaus Bauer",
        location: "Frankfurt, DE",
        rating: 5,
        title: "Trade operations are significantly more efficient since launch",
        body: "Before ShopifyTasker our trade team was managing orders manually in spreadsheets. Gaurank built the wholesale side properly and now everything processes through Shopify automatically. The operational difference is significant. Highly recommend.",
        daysAgo: 27,
        verified: true,
      },
      {
        name: "Li Wei",
        location: "Shanghai, CN",
        rating: 4,
        title: "Quality of wholesale enquiries improved the moment we launched",
        body: "The trade application form Ayushi built properly vets buyers before they get access which means the quality of our wholesale enquiries improved straight away. The whole development was done to a really high standard. Would recommend ShopifyTasker.",
        daysAgo: 42,
        verified: true,
      },
    ],
  },

  // ─── FOOD SUPPLY ───────────────────────────────────────────────────────────
  {
    slug: "food-supply",
    aggregateRating: 4.9,
    reviewCount: 40,
    reviews: [
      {
        name: "Ahmed Hassan",
        location: "Dubai, UAE",
        rating: 5,
        title: "B2B revenue up 55% since our new food supply website went live",
        body: "B2B revenue is up 55 percent since Vidi built the full food supply website with standing order scheduling for restaurants and caterers. When repeat ordering is built properly clients just keep coming back automatically. Brilliant work from ShopifyTasker.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Susan Carpenter",
        location: "Birmingham, UK",
        rating: 5,
        title: "Compliant, professional and easy for our team to manage day to day",
        body: "Compliance was designed in from the start not bolted on after. Ranu built every allergen and nutritional section into the product templates from day one. The whole store is professional and our team manages it without ever needing a developer.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Rafael Costa",
        location: "Porto, PT",
        rating: 5,
        title: "Order processing time is down 60%. Automation changed everything.",
        body: "Order processing time is down 60 percent since Gaurank built the standing orders and cold chain delivery automation. We was doing so much manually before. Now it just runs. Thats the difference between a site that exists and one built to run a business.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Mei Chen",
        location: "Vancouver, BC",
        rating: 5,
        title: "Not one shipment error since launch. The cold chain setup is exactly right.",
        body: "Temperature sensitive shipping is unforgiving, one wrong configuration means spoiled product and an angry client. Ayushi built the cold chain setup exactly right from day one. Not one shipment has gone wrong since we launched. Genuinely impressive.",
        daysAgo: 39,
        verified: true,
      },
    ],
  },

  // ─── CANDLE BUSINESS ───────────────────────────────────────────────────────
  {
    slug: "candle-business",
    aggregateRating: 4.9,
    reviewCount: 35,
    reviews: [
      {
        name: "Lucy Pearson",
        location: "Edinburgh, UK",
        rating: 5,
        title: "Wedding favour candles with custom labels are now our best-selling product",
        body: "The personalised label feature with live preview that Vidi built opened up a whole revenue stream we hadn't properly tapped before. Wedding favour candles went from something we offered to our best selling product. Really clever work. Use ShopifyTasker.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Céline Aubert",
        location: "Bordeaux, France",
        rating: 5,
        title: "Customers say they could almost smell the candles through the screen",
        body: "Customers actually leave reviews saying they could almost smell the candles through the screen. Ranu built scent profiles with top middle and base notes on every product page. When a website creates a sensory impression the development has done its job.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Priya Nair",
        location: "London, UK",
        rating: 5,
        title: "Retail, wholesale and workshops all working from one website. Transformed how we operate.",
        body: "Had retail wholesale and workshop bookings across three separate systems before. Gaurank built all of it into one website and the operational simplification alone was worth the investment. Everything in one place now and it all just works together.",
        daysAgo: 25,
        verified: true,
      },
      {
        name: "Sarah Muller",
        location: "Zurich, CH",
        rating: 5,
        title: "Workshop bookings increased significantly once the booking flow was built properly",
        body: "Before ShopifyTasker most people was dropping off the workshop booking page before completing. Ayushi built bookings into the same checkout flow as the products and bookings increased significantly straight away. Right fix for the right problem.",
        daysAgo: 40,
        verified: true,
      },
    ],
  },
];

export function getReviews(slug: string): IndustryReviewData | null {
  return reviewsBySlug.find((r) => r.slug === slug) ?? null;
}
