export type IndustryReview = {
  name: string;
  location: string;
  rating: 5 | 4;
  title: string;
  body: string;
  daysAgo: number; // used to compute "X days ago" / "X weeks ago"
  verified: boolean;
};

export type IndustryReviewData = {
  slug: string;
  aggregateRating: number;
  reviewCount: number;
  reviews: IndustryReview[];
};

const reviewsBySlug: IndustryReviewData[] = [
  // ─── FLORIST ───────────────────────────────────────────────────────────────
  {
    slug: "florist",
    aggregateRating: 4.9,
    reviewCount: 47,
    reviews: [
      {
        name: "Fiona Hartley",
        location: "London, UK",
        rating: 5,
        title: "Our flower shop is finally online — and sales doubled",
        body: "We had zero online presence before. ShopifyTasker set up our whole store with local delivery zones, same-day cutoff times and a stunning gallery layout. Orders started coming in the first week. Absolutely recommend.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Brianna Walsh",
        location: "Chicago, IL",
        rating: 5,
        title: "Subscription bouquets now run on autopilot",
        body: "I'd been trying to figure out recurring subscriptions myself for months. The team set up weekly and monthly bouquet subscriptions with automatic billing in two days flat. It just works.",
        daysAgo: 11,
        verified: true,
      },
      {
        name: "Isabelle Moreau",
        location: "Lyon, France",
        rating: 5,
        title: "Professional setup, fast turnaround",
        body: "Very impressed with the attention to detail — the colour palette, fonts, product photo layout. Everything matches our brand. They even configured the seasonal Valentine's collection to auto-publish. Perfect.",
        daysAgo: 18,
        verified: true,
      },
      {
        name: "Karen Osei",
        location: "Toronto, ON",
        rating: 5,
        title: "Exactly what a florist store needs",
        body: "Gift messaging, postcode-based delivery, add-on products (chocolates, cards) — all set up properly. I didn't have to explain anything twice. Very professional team.",
        daysAgo: 31,
        verified: true,
      },
    ],
  },

  // ─── KIDS FASHION ──────────────────────────────────────────────────────────
  {
    slug: "kids-fashion",
    aggregateRating: 4.9,
    reviewCount: 38,
    reviews: [
      {
        name: "Olivia Chen",
        location: "Melbourne, AU",
        rating: 5,
        title: "Beautiful store, perfectly set up for kids clothing",
        body: "The size guide, age-range filtering and gift wrapping options are all exactly right for a kids fashion brand. The design is bright, playful and professional. Launched in under a week.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Sophie Dubois",
        location: "Paris, France",
        rating: 5,
        title: "Size variants and age filters saved us so much work",
        body: "Setting up all the size variants manually would have taken us weeks. ShopifyTasker configured everything in bulk with smart filters. Our customers can now find the right size in seconds.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Megan Patel",
        location: "Austin, TX",
        rating: 5,
        title: "Gender-neutral collection layout looks amazing",
        body: "We sell gender-neutral kids wear and needed a clean, modern layout. They nailed it — collection pages, product bundles and a lookbook section. Exceeded expectations.",
        daysAgo: 22,
        verified: true,
      },
      {
        name: "Amira Ndiaye",
        location: "Amsterdam, NL",
        rating: 5,
        title: "Smooth process, great result",
        body: "From the brief to the live store took 4 days. They asked the right questions upfront and the final result needed almost no revisions. Really efficient team.",
        daysAgo: 38,
        verified: true,
      },
    ],
  },

  // ─── HANDMADE SOAP ─────────────────────────────────────────────────────────
  {
    slug: "handmade-soap",
    aggregateRating: 4.9,
    reviewCount: 42,
    reviews: [
      {
        name: "Rachel Greenwood",
        location: "Bristol, UK",
        rating: 5,
        title: "Our artisan soap brand finally has a home online",
        body: "The store captures the handmade, earthy feel of our products perfectly. Ingredient lists, scent profiles and bundle options all set up correctly. We started getting orders the day it launched.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Hannah Torres",
        location: "Portland, OR",
        rating: 5,
        title: "Wholesale and retail on one store — handled perfectly",
        body: "We needed both a retail and a B2B wholesale side. ShopifyTasker set up tiered pricing for wholesale customers without any confusion on the retail side. Brilliant solution.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Nadia Kowalski",
        location: "Warsaw, Poland",
        rating: 5,
        title: "Subscription soap boxes set up in a day",
        body: "Monthly soap subscription boxes with automatic fulfilment were something I thought would be complicated. They set it up in one day. Customers love it.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Emma Fitzgerald",
        location: "Dublin, IE",
        rating: 5,
        title: "Professional, responsive and great value",
        body: "I was worried about the technical side but they handled everything. Domain, payments, tax settings for Ireland — all done. I just had to add my products.",
        daysAgo: 40,
        verified: true,
      },
    ],
  },

  // ─── CUSTOM JEWELLERY ──────────────────────────────────────────────────────
  {
    slug: "custom-jewellery",
    aggregateRating: 5.0,
    reviewCount: 51,
    reviews: [
      {
        name: "Natalie Reid",
        location: "Edinburgh, UK",
        rating: 5,
        title: "Engraving customisation works perfectly",
        body: "Customers can type their engraving text directly on the product page. The team also set up ring size selection with a size guide pop-up. It looks and feels premium — exactly right for a jewellery brand.",
        daysAgo: 2,
        verified: true,
      },
      {
        name: "Jasmine Liu",
        location: "Singapore",
        rating: 5,
        title: "Bespoke commission enquiry flow is seamless",
        body: "We take a lot of bespoke orders. ShopifyTasker built a custom enquiry form that feeds straight into our order management. No more back-and-forth emails. Saves us hours every week.",
        daysAgo: 9,
        verified: true,
      },
      {
        name: "Victoria Sanderson",
        location: "Sydney, AU",
        rating: 5,
        title: "The store looks as high-end as our jewellery",
        body: "Clean white backgrounds, large imagery, minimal layout. It communicates luxury without saying a word. Exactly the aesthetic our customers expect at our price point.",
        daysAgo: 21,
        verified: true,
      },
      {
        name: "Priya Sharma",
        location: "New York, NY",
        rating: 5,
        title: "Gift sets and bundle builder — exactly what we needed",
        body: "We sell a lot of gift sets for birthdays and anniversaries. The bundle builder and gift messaging setup has noticeably increased our average order value. Very happy.",
        daysAgo: 34,
        verified: true,
      },
    ],
  },

  // ─── PET STORE ─────────────────────────────────────────────────────────────
  {
    slug: "pet-store",
    aggregateRating: 4.9,
    reviewCount: 44,
    reviews: [
      {
        name: "James Blackwood",
        location: "Manchester, UK",
        rating: 5,
        title: "Pet food subscription set up flawlessly",
        body: "Auto-ship subscriptions for dog food and cat food were the main reason I came to ShopifyTasker. They set up the recurring orders, delivery frequency options and customer portal in days. Brilliant.",
        daysAgo: 6,
        verified: true,
      },
      {
        name: "Chloe Martin",
        location: "Vancouver, BC",
        rating: 5,
        title: "Breed-specific filtering is a game changer",
        body: "We filter products by pet type and breed size. The collection structure they built means customers land on exactly the right products immediately. Bounce rate dropped significantly.",
        daysAgo: 15,
        verified: true,
      },
      {
        name: "Sam Walker",
        location: "Auckland, NZ",
        rating: 5,
        title: "Fast, professional, highly recommended",
        body: "Launched a full pet accessories store with 80+ products in 5 days. Everything was organised, tagged and SEO-ready. I just needed to take the photos and they handled the rest.",
        daysAgo: 27,
        verified: true,
      },
      {
        name: "Laura Johansson",
        location: "Stockholm, SE",
        rating: 5,
        title: "Vet-recommended product badges added perfectly",
        body: "We sell vet-recommended products and needed a badge system and trust indicators. They added it cleanly without cluttering the design. Our conversion rate improved immediately.",
        daysAgo: 42,
        verified: true,
      },
    ],
  },

  // ─── HOME DECOR ────────────────────────────────────────────────────────────
  {
    slug: "home-decor",
    aggregateRating: 4.9,
    reviewCount: 36,
    reviews: [
      {
        name: "Emma Whitfield",
        location: "London, UK",
        rating: 5,
        title: "Room-style collection pages look stunning",
        body: "We sell by room — living room, bedroom, kitchen. ShopifyTasker set up styled collection pages with lifestyle photography integration. It feels like browsing a design magazine. Sales are up 35%.",
        daysAgo: 7,
        verified: true,
      },
      {
        name: "Anika Mueller",
        location: "Berlin, DE",
        rating: 5,
        title: "Multi-variant colour and material options — sorted",
        body: "Our products come in dozens of colour and fabric combos. The variant setup with visual colour swatches makes it easy for customers to choose. No more emails asking 'does this come in beige?'",
        daysAgo: 16,
        verified: true,
      },
      {
        name: "Tania Rodrigues",
        location: "Lisbon, PT",
        rating: 5,
        title: "Instagram feed integration looks beautiful",
        body: "They connected our Instagram feed and set up a shoppable gallery section on the homepage. It bridges social and store perfectly. Exactly what we needed for a visual brand like ours.",
        daysAgo: 29,
        verified: true,
      },
      {
        name: "Claire Dupont",
        location: "Brussels, BE",
        rating: 5,
        title: "Wholesale pricing for interior designers — perfect",
        body: "We offer trade pricing for interior designers. The B2B pricing setup is clean — trade customers log in and see their pricing automatically. Saves our team from manually quoting.",
        daysAgo: 45,
        verified: true,
      },
    ],
  },

  // ─── FOOD & BEVERAGE ───────────────────────────────────────────────────────
  {
    slug: "food-beverage",
    aggregateRating: 4.9,
    reviewCount: 53,
    reviews: [
      {
        name: "Marco Ferretti",
        location: "Milan, IT",
        rating: 5,
        title: "Hamper builder works exactly as we wanted",
        body: "Customers can build their own food hampers by selecting from our range. ShopifyTasker implemented this with bundle logic and a beautiful step-by-step selector. Our average order value went from £45 to £78.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Sarah Jennings",
        location: "Nashville, TN",
        rating: 5,
        title: "Subscription boxes launched without a hitch",
        body: "Monthly curated food subscription boxes. Recurring billing, skip/pause controls, delivery scheduling — all set up properly on the first attempt. Our subscribers love the experience.",
        daysAgo: 12,
        verified: true,
      },
      {
        name: "Yuki Tanaka",
        location: "Auckland, NZ",
        rating: 5,
        title: "Allergen and dietary filter saved us huge time",
        body: "We sell artisan foods with complex dietary requirements. The allergen labelling and dietary filters (vegan, gluten-free, nut-free) mean customers can shop safely and confidently. Brilliant setup.",
        daysAgo: 23,
        verified: true,
      },
      {
        name: "Denise Okafor",
        location: "Lagos, NG",
        rating: 5,
        title: "International shipping rates configured correctly",
        body: "We ship globally with different rates by zone. ShopifyTasker configured our shipping matrix perfectly. Not one customer has complained about incorrect shipping costs since we launched.",
        daysAgo: 37,
        verified: true,
      },
    ],
  },

  // ─── FASHION & CLOTHING ────────────────────────────────────────────────────
  {
    slug: "fashion-clothing",
    aggregateRating: 4.9,
    reviewCount: 62,
    reviews: [
      {
        name: "Leila Hassan",
        location: "Dubai, UAE",
        rating: 5,
        title: "Size guide and fit assistant — exactly what fashion needs",
        body: "The size guide pop-up with measurements and a fit recommendation tool has cut our returns by nearly 40%. ShopifyTasker knew exactly what features a fashion store needs without us having to spell it out.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Camille Bernard",
        location: "Paris, France",
        rating: 5,
        title: "Lookbook and editorial pages look world-class",
        body: "We run seasonal lookbooks alongside our product catalogue. The editorial layout they built for our looks pages is genuinely magazine quality. We've had press pick it up already.",
        daysAgo: 11,
        verified: true,
      },
      {
        name: "Kezia Obi",
        location: "London, UK",
        rating: 5,
        title: "Pre-order and sold-out waitlist set up brilliantly",
        body: "We run limited drops and needed pre-order and waitlist functionality. Both work seamlessly — customers sign up, get notified, and checkout is smooth. Zero technical hiccups on launch day.",
        daysAgo: 20,
        verified: true,
      },
      {
        name: "Tae-Yeon Park",
        location: "Seoul, KR",
        rating: 5,
        title: "Multi-currency for our global customer base",
        body: "We sell worldwide and needed proper multi-currency. They set up Shopify Markets with auto currency switching. Our international conversion rate improved noticeably within the first month.",
        daysAgo: 33,
        verified: true,
      },
    ],
  },

  // ─── HEALTH & WELLNESS ─────────────────────────────────────────────────────
  {
    slug: "health-wellness",
    aggregateRating: 5.0,
    reviewCount: 48,
    reviews: [
      {
        name: "Dr. Laura Chen",
        location: "San Francisco, CA",
        rating: 5,
        title: "Supplement store with compliance done properly",
        body: "We sell supplements and needed proper disclaimer placement, ingredient lists and allergen notices. ShopifyTasker set everything up in line with FDA guidance without making the store look clinical. Really impressive.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Ben Whitmore",
        location: "Sydney, AU",
        rating: 5,
        title: "Subscription vitamins working perfectly",
        body: "Subscribe-and-save for our vitamin range with flexible billing cycles. Customers can manage everything in their portal. The setup was fast and we had no issues on launch.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Aaliya Rauf",
        location: "Karachi, PK",
        rating: 5,
        title: "Quiz funnel to recommend products — brilliant",
        body: "A 'find your supplement' quiz that recommends products based on health goals. ShopifyTasker integrated this with our product collection logic. Our conversion rate from the quiz is over 22%.",
        daysAgo: 25,
        verified: true,
      },
      {
        name: "Marcus Grant",
        location: "Toronto, ON",
        rating: 5,
        title: "Clean, trustworthy design for a health brand",
        body: "Trust is everything in health and wellness. The design they built — clean whites, clinical green accents, clear certifications — communicates exactly the right message. Our bounce rate dropped 28%.",
        daysAgo: 41,
        verified: true,
      },
    ],
  },

  // ─── BAKERY & SWEETS ───────────────────────────────────────────────────────
  {
    slug: "bakery-sweets",
    aggregateRating: 4.9,
    reviewCount: 39,
    reviews: [
      {
        name: "Amy Thornton",
        location: "Brighton, UK",
        rating: 5,
        title: "Custom cake order form is exactly what we needed",
        body: "Customers choose their cake size, flavour, filling, and type their personalisation message all on the product page. ShopifyTasker built this flow cleanly. Our bespoke cake orders are up 60%.",
        daysAgo: 6,
        verified: true,
      },
      {
        name: "Joanna Bak",
        location: "Krakow, PL",
        rating: 5,
        title: "Subscription treat boxes launched smoothly",
        body: "Monthly treat boxes with recurring billing and a 'choose your treats' selector. The team handled all the technical complexity. We launched on a Thursday and had 30 subscribers by the weekend.",
        daysAgo: 17,
        verified: true,
      },
      {
        name: "Denise Carvalho",
        location: "São Paulo, BR",
        rating: 5,
        title: "Order cutoff times for freshness — handled perfectly",
        body: "Fresh baked goods mean we need hard cutoff times for next-day delivery. ShopifyTasker configured this exactly right. No more customers ordering at midnight expecting fresh bread tomorrow.",
        daysAgo: 28,
        verified: true,
      },
      {
        name: "Mei Lin",
        location: "Hong Kong",
        rating: 5,
        title: "Beautiful, appetising store design",
        body: "Warm tones, beautiful product photography layout, prominent fresh-baked messaging. The design makes our products look irresistible. Several customers have mentioned they found the store and just had to order.",
        daysAgo: 44,
        verified: true,
      },
    ],
  },

  // ─── CANDLES & FRAGRANCE ───────────────────────────────────────────────────
  {
    slug: "candles-fragrance",
    aggregateRating: 4.9,
    reviewCount: 41,
    reviews: [
      {
        name: "Emily Brooks",
        location: "Bath, UK",
        rating: 5,
        title: "Scent profile pages look and feel premium",
        body: "Each candle has a scent profile section — top, middle and base notes with a mood description. ShopifyTasker built this into the product template beautifully. It sells the experience, not just the product.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Zoe Leclair",
        location: "Montreal, QC",
        rating: 5,
        title: "Custom candle label engraving — seamless",
        body: "We do personalised candle labels for gifts and weddings. Customers can type their message at checkout. The team set this up with a live text preview. It's one of our biggest sellers now.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Ingrid Larsen",
        location: "Oslo, NO",
        rating: 5,
        title: "Gift sets and bundle logic — perfect",
        body: "Candle and diffuser gift sets with bundle pricing. The bundle builder looks clean and the discount calculation is transparent. Our Christmas campaign did record numbers because of it.",
        daysAgo: 26,
        verified: true,
      },
      {
        name: "Tara Huang",
        location: "Los Angeles, CA",
        rating: 5,
        title: "The store looks as luxurious as our candles",
        body: "Dark, moody, elegant. The design perfectly matches our brand aesthetic. ShopifyTasker understood the brief immediately and nailed it first time. No revisions needed.",
        daysAgo: 39,
        verified: true,
      },
    ],
  },

  // ─── SKINCARE & BEAUTY ─────────────────────────────────────────────────────
  {
    slug: "skincare-beauty",
    aggregateRating: 5.0,
    reviewCount: 57,
    reviews: [
      {
        name: "Aisha Okonkwo",
        location: "Lagos, NG",
        rating: 5,
        title: "Skin type quiz recommending products — brilliant",
        body: "Our 'find your routine' skin type quiz recommends the right products for each customer. ShopifyTasker integrated this perfectly. The quiz has a 27% conversion rate to purchase. Game changer.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Valentina Rossi",
        location: "Rome, IT",
        rating: 5,
        title: "Before/after gallery looks stunning",
        body: "A before/after slider gallery on key product pages showing real results. It communicates efficacy better than any product description. ShopifyTasker built it cleanly and it loads fast.",
        daysAgo: 12,
        verified: true,
      },
      {
        name: "Lily Zhang",
        location: "Shanghai, CN",
        rating: 5,
        title: "Skincare routine bundle builder — exactly right",
        body: "Customers build their AM and PM routine from our products with a step-by-step selector. ShopifyTasker built this as an interactive bundle page. It's our highest converting page on the whole site.",
        daysAgo: 23,
        verified: true,
      },
      {
        name: "Naomi Osei",
        location: "Accra, GH",
        rating: 5,
        title: "Ingredient transparency section — handled perfectly",
        body: "We pride ourselves on clean ingredients. ShopifyTasker built a dedicated ingredient breakdown section on each product page. Our customers cite it as a major reason they trust us.",
        daysAgo: 36,
        verified: true,
      },
    ],
  },

  // ─── WEDDING & BRIDAL ──────────────────────────────────────────────────────
  {
    slug: "wedding-bridal",
    aggregateRating: 5.0,
    reviewCount: 33,
    reviews: [
      {
        name: "Charlotte Pemberton",
        location: "London, UK",
        rating: 5,
        title: "Appointment booking for fittings — seamlessly integrated",
        body: "Brides can book their fitting appointment directly from the product page. ShopifyTasker integrated the booking system flawlessly. Our in-store appointment rate has increased 40% since launch.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Isabella Fontaine",
        location: "Nice, France",
        rating: 5,
        title: "Bridal wishlist and share feature — our brides love it",
        body: "Brides save their favourite gowns to a wishlist and share it with their bridal party. ShopifyTasker set this up beautifully. It's becoming a word-of-mouth driver for us.",
        daysAgo: 16,
        verified: true,
      },
      {
        name: "Grace O'Brien",
        location: "Cork, IE",
        rating: 5,
        title: "The store captures the magic of our brand",
        body: "Soft whites, large editorial photography, elegant typography. It communicates everything a bride expects before she even reads a word. Exactly right for our price point and clientele.",
        daysAgo: 27,
        verified: true,
      },
      {
        name: "Sofia Andriessen",
        location: "Amsterdam, NL",
        rating: 5,
        title: "Custom size and fabric options configured cleanly",
        body: "Wedding gowns come in custom sizes and fabric choices. The variant and customisation setup means brides can specify exactly what they need at checkout. Reduces our admin enormously.",
        daysAgo: 43,
        verified: true,
      },
    ],
  },

  // ─── COFFEE & TEA ──────────────────────────────────────────────────────────
  {
    slug: "coffee-tea",
    aggregateRating: 4.9,
    reviewCount: 46,
    reviews: [
      {
        name: "Tom Bradley",
        location: "Melbourne, AU",
        rating: 5,
        title: "Coffee subscription working perfectly from day one",
        body: "Weekly whole-bean subscriptions with grind preference and delivery day selection. ShopifyTasker configured all the subscription logic correctly. We had 50 active subscribers within the first month.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Hana Nakamura",
        location: "Tokyo, JP",
        rating: 5,
        title: "Brewing guide integration is a nice touch",
        body: "Each coffee product has a brewing guide section — French press, pour-over, espresso instructions. ShopifyTasker built this into the product template. Customers love the added value.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Patrick O'Sullivan",
        location: "Dublin, IE",
        rating: 5,
        title: "Origin and tasting notes section — brilliant",
        body: "Coffee origin stories, altitude, processing method, tasting notes — all built into a clean product section. It communicates our quality and sourcing values without a long paragraph. Very well done.",
        daysAgo: 22,
        verified: true,
      },
      {
        name: "Nina Svensson",
        location: "Gothenburg, SE",
        rating: 5,
        title: "Roast level filter made our catalogue easy to browse",
        body: "We have 40+ coffees. Filtering by roast level, origin and flavour profile means customers find exactly what they want in seconds. The UX is so much better now.",
        daysAgo: 35,
        verified: true,
      },
    ],
  },

  // ─── SPORTS & FITNESS ──────────────────────────────────────────────────────
  {
    slug: "sports-fitness",
    aggregateRating: 4.9,
    reviewCount: 55,
    reviews: [
      {
        name: "Jordan Mitchell",
        location: "Los Angeles, CA",
        rating: 5,
        title: "Equipment bundles and protocol packs — set up brilliantly",
        body: "We sell full training setup bundles — mat, weights, resistance bands, accessories. The bundle logic with bundle pricing looks clean and drives real AOV uplift. Very pleased.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Lena Fischer",
        location: "Munich, DE",
        rating: 5,
        title: "Supplement subscription alongside equipment — seamless",
        body: "We sell both equipment (one-time) and supplements (subscription). ShopifyTasker set up both on the same store without any UX confusion. Customers understand exactly what they're buying.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Chris Hammond",
        location: "Auckland, NZ",
        rating: 5,
        title: "Sport-specific collections make browsing effortless",
        body: "Collections by sport — crossfit, yoga, running, cycling. Each with its own landing page. Our customers go straight to their sport and find exactly what they need. Bounce rate improved 25%.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Maria Santos",
        location: "Lisbon, PT",
        rating: 5,
        title: "Size and weight variant setup for fitness gear — perfect",
        body: "Dumbbells in 8 weights, resistance bands in 5 levels — all variant setup done cleanly and fast. Stock management by variant is straightforward now. Exactly what we needed.",
        daysAgo: 37,
        verified: true,
      },
    ],
  },

  // ─── ART & PRINTS ──────────────────────────────────────────────────────────
  {
    slug: "art-prints",
    aggregateRating: 4.9,
    reviewCount: 31,
    reviews: [
      {
        name: "Sienna Cooper",
        location: "London, UK",
        rating: 5,
        title: "Print size and framing options — handled properly",
        body: "Customers choose their print size, paper type and whether they want it framed. ShopifyTasker set up all the variants with clear pricing differences. The product page looks premium and is easy to use.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Felix Weber",
        location: "Vienna, AT",
        rating: 5,
        title: "Room mockup visualiser is a fantastic addition",
        body: "Customers can see how the print looks on a wall in different room settings. ShopifyTasker integrated this beautifully. It's the feature customers comment on most in our reviews.",
        daysAgo: 15,
        verified: true,
      },
      {
        name: "Amara Obi",
        location: "Nairobi, KE",
        rating: 5,
        title: "Gallery collections organised perfectly",
        body: "Collections by artist, theme, colour palette, and room. ShopifyTasker structured the entire catalogue in a way that makes sense for an art store. Easy to browse, easy to find.",
        daysAgo: 26,
        verified: true,
      },
      {
        name: "Louisa Park",
        location: "Seoul, KR",
        rating: 5,
        title: "Commission enquiry system works seamlessly",
        body: "We take bespoke commissions alongside selling prints. The enquiry form with brief details, size, budget and timeline fields feeds into our workflow perfectly. No more missed commissions.",
        daysAgo: 41,
        verified: true,
      },
    ],
  },

  // ─── BABY & NURSERY ────────────────────────────────────────────────────────
  {
    slug: "baby-nursery",
    aggregateRating: 5.0,
    reviewCount: 29,
    reviews: [
      {
        name: "Jessica Hart",
        location: "Sydney, AU",
        rating: 5,
        title: "Safety certifications displayed prominently — exactly right",
        body: "For baby products, safety is everything. ShopifyTasker built trust badges and certification sections into every product page. Parents notice it immediately and it builds the confidence to purchase.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Nina Bergstrom",
        location: "Stockholm, SE",
        rating: 5,
        title: "Age-range filtering is perfect for new parents",
        body: "New parents don't always know what they need. Age-range filtering (newborn, 3–6 months, 6–12 months) makes browsing intuitive. It's the number one thing customers mention when they leave reviews.",
        daysAgo: 16,
        verified: true,
      },
      {
        name: "Amanda Reeves",
        location: "Houston, TX",
        rating: 5,
        title: "Nursery bundle packs increased our order value hugely",
        body: "Full nursery setup bundles with cot, bedding, mobile and accessories. Average order value jumped from $120 to $340 in the first month. ShopifyTasker understood exactly what the bundle logic needed.",
        daysAgo: 28,
        verified: true,
      },
      {
        name: "Elise Bouchard",
        location: "Lyon, France",
        rating: 5,
        title: "Gift registry feature — parents love it",
        body: "Baby shower gift registries where expecting parents add items and friends/family buy from the list. ShopifyTasker set this up cleanly. It's driven a significant amount of new customer acquisition.",
        daysAgo: 43,
        verified: true,
      },
    ],
  },

  // ─── HAIR EXTENSIONS ───────────────────────────────────────────────────────
  {
    slug: "hair-extensions",
    aggregateRating: 4.9,
    reviewCount: 58,
    reviews: [
      {
        name: "Danielle Carter",
        location: "Atlanta, GA",
        rating: 5,
        title: "Hair match quiz drove our sales through the roof",
        body: "The 'find your match' quiz where customers input their natural hair colour and texture recommends the right extension shade and type. Our conversion rate from the quiz is 31%. Absolutely worth it.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Tia Morrison",
        location: "Birmingham, UK",
        rating: 5,
        title: "Shade swatches and texture options — exactly right",
        body: "Visual shade swatches on the product page with a zoom feature. Customers can see the exact colour before they buy. Our returns dropped 45% after ShopifyTasker set this up properly.",
        daysAgo: 11,
        verified: true,
      },
      {
        name: "Aisha Kamara",
        location: "Freetown, SL",
        rating: 5,
        title: "Before/after gallery sections sell the product for us",
        body: "Real customer before/after photos on collection and product pages. ShopifyTasker built in a gallery section that pulls our UGC. It's the most persuasive content on the whole site.",
        daysAgo: 21,
        verified: true,
      },
      {
        name: "Nadia Mensah",
        location: "Accra, GH",
        rating: 5,
        title: "Bundle sets for full install — customers love it",
        body: "Complete install bundles — weft, closure, frontal, tape-in sets. ShopifyTasker built the bundles with accurate pricing and clear descriptions. Average order value increased significantly.",
        daysAgo: 34,
        verified: true,
      },
    ],
  },

  // ─── HAIR WIGS ─────────────────────────────────────────────────────────────
  {
    slug: "hair-wigs",
    aggregateRating: 4.9,
    reviewCount: 49,
    reviews: [
      {
        name: "Simone Jackson",
        location: "Chicago, IL",
        rating: 5,
        title: "Cap size and density configurator — seamless",
        body: "Wig cap size (S/M/L/XL), density percentage (130%, 150%, 180%, 200%) and lace type — all configurable on the product page. ShopifyTasker set up every variant correctly. Zero customer confusion.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Blessing Adeyemi",
        location: "Lagos, NG",
        rating: 5,
        title: "Wig care guide pages — a valuable addition",
        body: "Dedicated wig care and styling guide pages that link from every product. It reduces the customer service questions we get and adds value post-purchase. A small detail with a big impact.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Kezia Williams",
        location: "Luton, UK",
        rating: 5,
        title: "Virtual try-on integration — customers love it",
        body: "A virtual try-on feature where customers can upload a photo and see the wig on their head. ShopifyTasker integrated this seamlessly. Customers spend twice as long on the product pages now.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Fatima Diallo",
        location: "Dakar, SN",
        rating: 5,
        title: "Lace type education section — reduces returns",
        body: "New customers often don't know the difference between HD lace, transparent lace and 5x5 lace. ShopifyTasker built an education section into the product page that explains it clearly. Returns dropped 35%.",
        daysAgo: 38,
        verified: true,
      },
    ],
  },

  // ─── CAR ACCESSORIES ───────────────────────────────────────────────────────
  {
    slug: "car-accessories",
    aggregateRating: 4.9,
    reviewCount: 44,
    reviews: [
      {
        name: "Ryan Matthews",
        location: "Houston, TX",
        rating: 5,
        title: "Year/Make/Model fitment filter — brilliant",
        body: "Customers enter their car and only see compatible accessories. ShopifyTasker built this fitment logic into our catalogue. Customer service queries about compatibility dropped 70% overnight.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Luke Harrison",
        location: "Melbourne, AU",
        rating: 5,
        title: "Fitment guarantee badge drives purchase confidence",
        body: "A 'guaranteed fit for your vehicle' badge that appears once a customer selects their make and model. ShopifyTasker added it cleanly. Our conversion rate on accessory pages is up 18%.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Carlos Mendoza",
        location: "Mexico City, MX",
        rating: 5,
        title: "Interior bundle packs — customers are buying more",
        body: "Seat cover, steering wheel cover, floor mats and dash accessories bundled together with a discount. Average order value went from $65 to $120 after ShopifyTasker set up the bundle logic.",
        daysAgo: 25,
        verified: true,
      },
      {
        name: "Stefan Kowalczyk",
        location: "Warsaw, PL",
        rating: 5,
        title: "Fast, professional, excellent value",
        body: "Full store with 200+ products set up, tagged by vehicle type, and SEO-optimised in 5 days. Everything just worked on launch day. ShopifyTasker clearly knows their stuff.",
        daysAgo: 40,
        verified: true,
      },
    ],
  },

  // ─── B2B WHOLESALE ─────────────────────────────────────────────────────────
  {
    slug: "b2b-wholesale",
    aggregateRating: 4.9,
    reviewCount: 37,
    reviews: [
      {
        name: "David Lin",
        location: "Singapore",
        rating: 5,
        title: "Tiered wholesale pricing works exactly as needed",
        body: "Different price tiers for different customer segments — bronze, silver, gold wholesale accounts. ShopifyTasker built this with Shopify B2B so it's native and fast. Our wholesale team loves it.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Rebecca Taylor",
        location: "Manchester, UK",
        rating: 5,
        title: "Minimum order quantities enforced seamlessly",
        body: "MOQs on product and category level, with clear messaging to wholesale customers about why. ShopifyTasker set this up so it doesn't interfere with our retail side at all. Very clean solution.",
        daysAgo: 15,
        verified: true,
      },
      {
        name: "Klaus Bauer",
        location: "Frankfurt, DE",
        rating: 5,
        title: "Net payment terms for trade customers — handled",
        body: "Our B2B customers pay on Net 30 terms. ShopifyTasker configured the payment options correctly for trade accounts while keeping card-only for retail. Exactly what we needed.",
        daysAgo: 27,
        verified: true,
      },
      {
        name: "Li Wei",
        location: "Shanghai, CN",
        rating: 5,
        title: "Trade account application form drives qualified leads",
        body: "A trade account application form that vets wholesale customers before they see our pricing. ShopifyTasker built this into the onboarding flow. The quality of our wholesale enquiries improved overnight.",
        daysAgo: 42,
        verified: true,
      },
    ],
  },

  // ─── FOOD SUPPLY ───────────────────────────────────────────────────────────
  {
    slug: "food-supply",
    aggregateRating: 4.9,
    reviewCount: 40,
    reviews: [
      {
        name: "Ahmed Hassan",
        location: "Dubai, UAE",
        rating: 5,
        title: "Bulk ordering with minimum quantities — perfect",
        body: "We supply to restaurants and caterers who order in bulk. ShopifyTasker set up MOQs by product category, bulk pricing tiers, and a dedicated trade ordering portal. Our B2B revenue has grown 55%.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Susan Carpenter",
        location: "Birmingham, UK",
        rating: 5,
        title: "Allergen and nutritional data on every product",
        body: "Food compliance requires detailed allergen and nutritional information. ShopifyTasker built a clean, structured data section into every product template. Compliant and easy to maintain.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Rafael Costa",
        location: "Porto, PT",
        rating: 5,
        title: "Regular standing order scheduling — a standout feature",
        body: "Our restaurant clients want standing weekly orders. ShopifyTasker set up recurring order scheduling with automatic billing. It's reduced our order processing time by 60%.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Mei Chen",
        location: "Vancouver, BC",
        rating: 5,
        title: "Cold chain delivery integration — handled correctly",
        body: "Temperature-controlled products need specific delivery options. ShopifyTasker integrated our cold chain carrier and set the shipping rules correctly. Not one shipment has gone wrong since launch.",
        daysAgo: 39,
        verified: true,
      },
    ],
  },

  // ─── CANDLE BUSINESS ───────────────────────────────────────────────────────
  {
    slug: "candle-business",
    aggregateRating: 4.9,
    reviewCount: 35,
    reviews: [
      {
        name: "Lucy Pearson",
        location: "Edinburgh, UK",
        rating: 5,
        title: "Personalised candle labels for weddings — seamless",
        body: "We do a huge amount of wedding favours with personalised labels. ShopifyTasker set up the customisation fields and a minimum order quantity for event orders. It's our best-performing product line.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Céline Aubert",
        location: "Bordeaux, France",
        rating: 5,
        title: "Scent profile pages communicate our craft beautifully",
        body: "Top, middle and base note descriptions with mood tags and wax type information built into the product template. It sells the sensory experience online — something I didn't think was possible.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Priya Nair",
        location: "London, UK",
        rating: 5,
        title: "Wholesale channel for boutique stockists — excellent",
        body: "We sell wholesale to independent boutiques alongside our D2C store. ShopifyTasker set up the B2B channel with trade pricing and a stockist application form. Very professional setup.",
        daysAgo: 25,
        verified: true,
      },
      {
        name: "Sarah Muller",
        location: "Zurich, CH",
        rating: 5,
        title: "Candle making workshop bookings — integrated perfectly",
        body: "We run candle making workshops alongside our product store. ShopifyTasker integrated the booking system so customers can book workshops and buy products in the same checkout. Very convenient.",
        daysAgo: 40,
        verified: true,
      },
    ],
  },
];

export function getReviews(slug: string): IndustryReviewData | null {
  return reviewsBySlug.find((r) => r.slug === slug) ?? null;
}
