export type IndustryReview = {
  name: string;
  location: string;
  rating: 5 | 4;
  title: string;
  body: string;
  daysAgo: number;
  verified: boolean;
};

export type IndustryReviewData = {
  slug: string;
  aggregateRating: number;
  reviewCount: number;
  reviews: IndustryReview[];
};

const reviewsBySlug: IndustryReviewData[] = [
  // ─── FLORIST ───────────────────────────────────────────────────────────────
  {
    slug: "florist",
    aggregateRating: 4.9,
    reviewCount: 47,
    reviews: [
      {
        name: "Fiona Hartley",
        location: "London, UK",
        rating: 5,
        title: "Vidi built exactly what our flower shop needed",
        body: "Vidi from ShopifyTasker set up our entire Shopify website — product pages, local delivery zones, same-day cutoff logic, the works. It wasn't just a basic setup, it was built properly for a florist business. We had orders coming in the first week. Honestly couldn't be happier.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Brianna Walsh",
        location: "Chicago, IL",
        rating: 5,
        title: "Shopify website setup done right, first time",
        body: "I'd been putting off getting a proper website because I didn't know where to start. ShopifyTasker took care of everything — theme, products, subscriptions, payment setup. Ranu was really easy to work with and explained each step. The store looks professional and works perfectly.",
        daysAgo: 11,
        verified: true,
      },
      {
        name: "Isabelle Moreau",
        location: "Lyon, France",
        rating: 5,
        title: "Full Shopify development for our flower boutique",
        body: "We needed more than just a template dropped online — we needed a real Shopify development partner. Gaurank handled everything from the theme customisation to the delivery logic to the seasonal collections. Communication was great, delivery was fast. Absolutely recommend ShopifyTasker.",
        daysAgo: 18,
        verified: true,
      },
      {
        name: "Karen Osei",
        location: "Toronto, ON",
        rating: 5,
        title: "ShopifyTasker delivered a store I'm proud of",
        body: "Ayushi from ShopifyTasker was brilliant throughout the whole setup. She understood what a florist store needs — gift messaging, add-on products, delivery zones — without me having to spell everything out. The finished store looks stunning and performs really well on mobile.",
        daysAgo: 31,
        verified: true,
      },
    ],
  },

  // ─── KIDS FASHION ──────────────────────────────────────────────────────────
  {
    slug: "kids-fashion",
    aggregateRating: 4.9,
    reviewCount: 38,
    reviews: [
      {
        name: "Olivia Chen",
        location: "Melbourne, AU",
        rating: 5,
        title: "Ranu built our kids clothing store from scratch",
        body: "Ranu from ShopifyTasker did a full Shopify website setup and development for our kids fashion brand. Size guides, age-range filtering, gender-neutral collections — all set up properly. The store launched in 5 days and it looks genuinely professional. Really impressed.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Sophie Dubois",
        location: "Paris, France",
        rating: 5,
        title: "ShopifyTasker understood our brand without much direction",
        body: "I gave them a brief and Vidi came back with a store that felt right for our brand immediately. Clean layout, proper variant setup for sizes and colours, bundle packs for gift buyers. The whole Shopify website development was handled end to end. Very smooth experience.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Megan Patel",
        location: "Austin, TX",
        rating: 5,
        title: "Full store development, not just a basic setup",
        body: "I'd tried setting up Shopify myself and gave up after a week. ShopifyTasker — specifically Gaurank — took over and delivered a proper store with working collections, filters, lookbook pages and everything. It's exactly what I wanted and I didn't have to figure anything out myself.",
        daysAgo: 22,
        verified: true,
      },
      {
        name: "Amira Ndiaye",
        location: "Amsterdam, NL",
        rating: 5,
        title: "Fast, thorough Shopify setup — highly recommend",
        body: "Ayushi handled our Shopify website setup from start to finish in under a week. She asked the right questions upfront and the revisions we needed were minor. The store is fast, looks great on mobile, and everything works exactly as it should. ShopifyTasker knows what they're doing.",
        daysAgo: 38,
        verified: true,
      },
    ],
  },

  // ─── HANDMADE SOAP ─────────────────────────────────────────────────────────
  {
    slug: "handmade-soap",
    aggregateRating: 4.9,
    reviewCount: 42,
    reviews: [
      {
        name: "Rachel Greenwood",
        location: "Bristol, UK",
        rating: 5,
        title: "Vidi built a store that captures our handmade brand perfectly",
        body: "Vidi from ShopifyTasker did a full Shopify website setup for our soap business. The design feels artisan and earthy — exactly right for our brand. Ingredient sections, scent descriptions, bundle options all set up properly. We started getting orders the day it went live.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Hannah Torres",
        location: "Portland, OR",
        rating: 5,
        title: "ShopifyTasker handled our wholesale + retail setup brilliantly",
        body: "We needed both a retail storefront and a B2B wholesale side on one Shopify store. I wasn't sure it was possible cleanly. Ranu from ShopifyTasker set it up perfectly — tiered pricing for trade customers, clean retail experience for everyone else. Exactly what we needed.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Nadia Kowalski",
        location: "Warsaw, Poland",
        rating: 5,
        title: "Subscription boxes live in a day — proper Shopify development",
        body: "Monthly soap subscription boxes with automatic billing, skip/pause controls and a proper customer portal. Gaurank got this all set up in one day. I'd spent weeks trying to figure it out myself. ShopifyTasker just gets it done.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Emma Fitzgerald",
        location: "Dublin, IE",
        rating: 5,
        title: "Full Shopify website setup, I just had to add my products",
        body: "Ayushi set up everything — domain connection, payment gateway, Irish VAT rates, mobile-optimised design, collections. I literally just had to upload my product photos. That's exactly the service I needed. Brilliant from start to finish.",
        daysAgo: 40,
        verified: true,
      },
    ],
  },

  // ─── CUSTOM JEWELLERY ──────────────────────────────────────────────────────
  {
    slug: "custom-jewellery",
    aggregateRating: 5.0,
    reviewCount: 51,
    reviews: [
      {
        name: "Natalie Reid",
        location: "Edinburgh, UK",
        rating: 5,
        title: "Vidi nailed the engraving customisation on our jewellery store",
        body: "Vidi from ShopifyTasker built out our entire jewellery Shopify website — engraving text input on product pages, ring size selector with a size guide modal, high-end minimal design. The whole development was done in under a week and it looks absolutely premium.",
        daysAgo: 2,
        verified: true,
      },
      {
        name: "Jasmine Liu",
        location: "Singapore",
        rating: 5,
        title: "ShopifyTasker built the bespoke commission flow we needed",
        body: "We take a lot of custom jewellery commissions. Ranu built a proper enquiry flow into our Shopify store — customers submit their brief, budget and timeline and it feeds straight into our workflow. Saves us hours of back-and-forth every week. Genuinely excellent work.",
        daysAgo: 9,
        verified: true,
      },
      {
        name: "Victoria Sanderson",
        location: "Sydney, AU",
        rating: 5,
        title: "The store looks as high-end as our jewellery — thanks Gaurank",
        body: "Gaurank from ShopifyTasker understood immediately that our store needed to communicate luxury. The design, typography, whitespace — it all feels right for a premium jewellery brand. Several customers have said the website made them trust us before they even looked at the prices.",
        daysAgo: 21,
        verified: true,
      },
      {
        name: "Priya Sharma",
        location: "New York, NY",
        rating: 5,
        title: "Full Shopify development, everything just works",
        body: "Ayushi from ShopifyTasker did a full website setup and development for our jewellery brand. Gift sets, bundle builder, personalisation fields, payment setup, SEO basics — all included. It's been live three months and we've had zero technical issues. Really solid work.",
        daysAgo: 34,
        verified: true,
      },
    ],
  },

  // ─── PET STORE ─────────────────────────────────────────────────────────────
  {
    slug: "pet-store",
    aggregateRating: 4.9,
    reviewCount: 44,
    reviews: [
      {
        name: "James Blackwood",
        location: "Manchester, UK",
        rating: 5,
        title: "Ranu set up our pet food subscription properly",
        body: "Auto-ship subscriptions for our dog and cat food range — different billing frequencies, customer portal, delivery scheduling. Ranu from ShopifyTasker got the whole thing working in two days. Our subscription revenue is now our biggest income stream. Brilliant.",
        daysAgo: 6,
        verified: true,
      },
      {
        name: "Chloe Martin",
        location: "Vancouver, BC",
        rating: 5,
        title: "ShopifyTasker built our store the way a pet brand should work",
        body: "Vidi did a full Shopify website setup and development for our pet accessories store. Breed filtering, pet type collections, bundle deals — all set up properly. The store makes it easy for customers to find what's right for their pet. Really thoughtful build.",
        daysAgo: 15,
        verified: true,
      },
      {
        name: "Sam Walker",
        location: "Auckland, NZ",
        rating: 5,
        title: "80 products, full store, live in 5 days",
        body: "Gaurank from ShopifyTasker set up our entire pet store — 80+ products properly organised, tagged, SEO-optimised and looking great. I just needed to add photos. The whole Shopify development was fast and the quality was really high. Would absolutely use ShopifyTasker again.",
        daysAgo: 27,
        verified: true,
      },
      {
        name: "Laura Johansson",
        location: "Stockholm, SE",
        rating: 5,
        title: "Ayushi understood exactly what our pet brand needed",
        body: "Ayushi from ShopifyTasker handled our full website setup. Vet-recommended badges, trust indicators, subscription logic for monthly food boxes — she set it all up without being asked twice. The store launched cleanly and our conversion rate has been strong from day one.",
        daysAgo: 42,
        verified: true,
      },
    ],
  },

  // ─── HOME DECOR ────────────────────────────────────────────────────────────
  {
    slug: "home-decor",
    aggregateRating: 4.9,
    reviewCount: 36,
    reviews: [
      {
        name: "Emma Whitfield",
        location: "London, UK",
        rating: 5,
        title: "Vidi built a home decor store that actually sells",
        body: "Vidi from ShopifyTasker developed our Shopify website from scratch — room-based collection pages, lifestyle photography layout, Instagram feed integration, colour swatch variants. It looks like a proper design brand online now, not just a Shopify template. Sales are up 35%.",
        daysAgo: 7,
        verified: true,
      },
      {
        name: "Anika Mueller",
        location: "Berlin, DE",
        rating: 5,
        title: "ShopifyTasker handled every detail of our store build",
        body: "Our products come in dozens of colour and fabric combinations. Ranu set up the visual colour swatch system so customers can see exactly what they're getting before buying. It sounds simple but makes a huge difference to the shopping experience. Very happy with ShopifyTasker.",
        daysAgo: 16,
        verified: true,
      },
      {
        name: "Tania Rodrigues",
        location: "Lisbon, PT",
        rating: 5,
        title: "Gaurank built out our full Shopify website and development",
        body: "Gaurank did our entire Shopify website setup and development. Shoppable Instagram feed, styled collection pages, newsletter integration, mobile optimisation — everything. It genuinely looks and feels premium. Several customers have commented on how nice the website is.",
        daysAgo: 29,
        verified: true,
      },
      {
        name: "Claire Dupont",
        location: "Brussels, BE",
        rating: 5,
        title: "Trade pricing for interior designers — set up cleanly by Ayushi",
        body: "We sell to both retail customers and interior designers. Ayushi from ShopifyTasker set up the B2B trade pricing so designers log in and see their prices automatically. The retail side is completely unaffected. It's a clean solution that saves our team loads of time.",
        daysAgo: 45,
        verified: true,
      },
    ],
  },

  // ─── FOOD & BEVERAGE ───────────────────────────────────────────────────────
  {
    slug: "food-beverage",
    aggregateRating: 4.9,
    reviewCount: 53,
    reviews: [
      {
        name: "Marco Ferretti",
        location: "Milan, IT",
        rating: 5,
        title: "Vidi from ShopifyTasker built our hamper builder perfectly",
        body: "Customers build their own food hampers step by step on our product page. Vidi implemented the bundle logic beautifully — it's interactive, it looks great, and our average order value went from €45 to €78 in the first month. That's what a proper Shopify development looks like.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Sarah Jennings",
        location: "Nashville, TN",
        rating: 5,
        title: "Subscription food boxes launched without a hitch — thanks Ranu",
        body: "Monthly curated food subscription boxes — recurring billing, skip and pause controls, delivery scheduling. Ranu from ShopifyTasker got all of this working on the first attempt. We had 50 active subscribers in the first month. The Shopify website setup exceeded what I expected.",
        daysAgo: 12,
        verified: true,
      },
      {
        name: "Yuki Tanaka",
        location: "Auckland, NZ",
        rating: 5,
        title: "ShopifyTasker built in allergen filtering we really needed",
        body: "We sell artisan foods with complex dietary requirements. Gaurank built proper allergen labelling and dietary filters into our Shopify store — vegan, gluten-free, nut-free all work properly. Customers shop with confidence now. It's a detail that really matters for a food brand.",
        daysAgo: 23,
        verified: true,
      },
      {
        name: "Denise Okafor",
        location: "Lagos, NG",
        rating: 5,
        title: "Ayushi handled our full Shopify website development",
        body: "Ayushi from ShopifyTasker did our complete Shopify website setup — international shipping zones, multi-currency, product catalogue setup, payment gateway. We ship globally and the shipping matrix was complex. She configured it perfectly. Not one issue since we launched.",
        daysAgo: 37,
        verified: true,
      },
    ],
  },

  // ─── FASHION & CLOTHING ────────────────────────────────────────────────────
  {
    slug: "fashion-clothing",
    aggregateRating: 4.9,
    reviewCount: 62,
    reviews: [
      {
        name: "Leila Hassan",
        location: "Dubai, UAE",
        rating: 5,
        title: "Vidi built our fashion store the way it should be built",
        body: "Vidi from ShopifyTasker did a full Shopify website setup and development for our clothing brand. Size guide with measurements, fit recommendation tool, pre-order for limited drops, multi-currency for our international customers. Our returns dropped 40% in the first two months. Brilliant work.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Camille Bernard",
        location: "Paris, France",
        rating: 5,
        title: "ShopifyTasker built lookbook pages that feel magazine quality",
        body: "Ranu developed our editorial lookbook pages alongside the main product catalogue. The layout, typography, full-width imagery — it genuinely looks like a fashion editorial. Press have picked it up. That kind of quality Shopify website development is hard to find.",
        daysAgo: 11,
        verified: true,
      },
      {
        name: "Kezia Obi",
        location: "London, UK",
        rating: 5,
        title: "Gaurank handled our limited drop launch perfectly",
        body: "We run limited drops and needed pre-order and sold-out waitlist functionality built into our Shopify store. Gaurank from ShopifyTasker set it all up — notifications, checkout flow, everything. Zero issues on our last launch day. ShopifyTasker genuinely knows Shopify development.",
        daysAgo: 20,
        verified: true,
      },
      {
        name: "Tae-Yeon Park",
        location: "Seoul, KR",
        rating: 5,
        title: "Ayushi set up Shopify Markets for our global store",
        body: "We sell worldwide and needed proper multi-currency and localised shopping. Ayushi from ShopifyTasker configured Shopify Markets for us — auto currency switching, localised pricing, correct tax handling per region. Our international conversion rate is noticeably higher now.",
        daysAgo: 33,
        verified: true,
      },
    ],
  },

  // ─── HEALTH & WELLNESS ─────────────────────────────────────────────────────
  {
    slug: "health-wellness",
    aggregateRating: 5.0,
    reviewCount: 48,
    reviews: [
      {
        name: "Dr. Laura Chen",
        location: "San Francisco, CA",
        rating: 5,
        title: "Vidi built our supplement store compliantly and beautifully",
        body: "Vidi from ShopifyTasker did a full Shopify website setup for our supplement brand — proper disclaimer placement, ingredient lists, allergen notices, all in line with FDA guidance. The store doesn't look clinical though. It looks premium and trustworthy. Really impressed.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Ben Whitmore",
        location: "Sydney, AU",
        rating: 5,
        title: "Subscribe-and-save working perfectly — thanks Ranu",
        body: "Ranu from ShopifyTasker set up subscribe-and-save for our vitamin range with flexible billing cycles and a full customer portal. The whole Shopify development was done in three days. We had no issues on launch and our subscription revenue is growing every month.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Aaliya Rauf",
        location: "Karachi, PK",
        rating: 5,
        title: "Gaurank built our product quiz — 22% conversion rate",
        body: "Gaurank from ShopifyTasker built a 'find your supplement' quiz into our Shopify store that recommends products based on health goals. It took a few days to develop properly. The quiz now converts at 22% to a purchase. That single feature has transformed our website.",
        daysAgo: 25,
        verified: true,
      },
      {
        name: "Marcus Grant",
        location: "Toronto, ON",
        rating: 5,
        title: "Ayushi built a health brand website that communicates trust",
        body: "Ayushi from ShopifyTasker understood that trust is everything in health and wellness. The design — clean whites, clear certifications, clinical but warm — communicates credibility before a customer reads a word. Our bounce rate dropped 28% after the new site went live.",
        daysAgo: 41,
        verified: true,
      },
    ],
  },

  // ─── BAKERY & SWEETS ───────────────────────────────────────────────────────
  {
    slug: "bakery-sweets",
    aggregateRating: 4.9,
    reviewCount: 39,
    reviews: [
      {
        name: "Amy Thornton",
        location: "Brighton, UK",
        rating: 5,
        title: "Vidi built our custom cake order flow — bespoke orders are up 60%",
        body: "Vidi from ShopifyTasker built the cake customisation flow on our product pages — customers choose size, flavour, filling, then type their personalisation message. It's smooth, it looks good, and our bespoke cake orders are up 60% since it launched. Proper Shopify development.",
        daysAgo: 6,
        verified: true,
      },
      {
        name: "Joanna Bak",
        location: "Krakow, PL",
        rating: 5,
        title: "ShopifyTasker launched our treat subscription in days",
        body: "Monthly treat boxes with recurring billing and a 'choose your treats' selector. Ranu handled all the technical complexity and got it live in two days. We launched on Thursday and had 30 subscribers by the weekend. ShopifyTasker just delivers.",
        daysAgo: 17,
        verified: true,
      },
      {
        name: "Denise Carvalho",
        location: "São Paulo, BR",
        rating: 5,
        title: "Gaurank configured our order cutoffs — no more midnight orders",
        body: "Fresh baked goods mean hard cutoff times for next-day delivery. Gaurank from ShopifyTasker configured this exactly right. No more customers ordering at midnight expecting fresh bread tomorrow. Such a specific problem that needed a specific solution — and ShopifyTasker nailed it.",
        daysAgo: 28,
        verified: true,
      },
      {
        name: "Mei Lin",
        location: "Hong Kong",
        rating: 5,
        title: "Ayushi built a bakery website that makes people hungry",
        body: "Ayushi from ShopifyTasker did our full Shopify website setup and development. Warm tones, beautiful product photography layout, fresh messaging throughout. Several customers have told me they found the website and just had to order. That's exactly what a bakery website should do.",
        daysAgo: 44,
        verified: true,
      },
    ],
  },

  // ─── CANDLES & FRAGRANCE ───────────────────────────────────────────────────
  {
    slug: "candles-fragrance",
    aggregateRating: 4.9,
    reviewCount: 41,
    reviews: [
      {
        name: "Emily Brooks",
        location: "Bath, UK",
        rating: 5,
        title: "Vidi built scent profile pages that actually sell the experience",
        body: "Vidi from ShopifyTasker built top, middle and base note descriptions with mood tags into our product template. It sells the sensory experience online — something I honestly didn't think was possible. Customers regularly mention the website in their reviews. Really great Shopify development.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Zoe Leclair",
        location: "Montreal, QC",
        rating: 5,
        title: "Ranu built our personalised candle label feature — best seller",
        body: "Ranu from ShopifyTasker built personalised candle label customisation with a live text preview. Customers type their message and see it on the label before ordering. That feature is now our best-selling product. ShopifyTasker thought about the user experience, not just the tech.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Ingrid Larsen",
        location: "Oslo, NO",
        rating: 5,
        title: "Gaurank handled our gift set bundles — record Christmas sales",
        body: "Candle and diffuser gift sets with clean bundle pricing and discount display. Gaurank from ShopifyTasker built this properly — the pricing is transparent, the bundle UI looks great. Our Christmas campaign was our best ever. ShopifyTasker's Shopify development made a real difference.",
        daysAgo: 26,
        verified: true,
      },
      {
        name: "Tara Huang",
        location: "Los Angeles, CA",
        rating: 5,
        title: "Ayushi got the brief immediately — dark, moody, luxurious",
        body: "Ayushi from ShopifyTasker understood our brand aesthetic immediately. Dark, moody, elegant — the Shopify website setup nailed it first time. No revisions needed. ShopifyTasker genuinely listens to what you want and delivers it, rather than just doing what's easy.",
        daysAgo: 39,
        verified: true,
      },
    ],
  },

  // ─── SKINCARE & BEAUTY ─────────────────────────────────────────────────────
  {
    slug: "skincare-beauty",
    aggregateRating: 5.0,
    reviewCount: 57,
    reviews: [
      {
        name: "Aisha Okonkwo",
        location: "Lagos, NG",
        rating: 5,
        title: "Vidi built our skin quiz — 27% conversion to purchase",
        body: "Vidi from ShopifyTasker built a 'find your routine' quiz that recommends products based on skin type and goals. It took a few days to develop properly and integrate with our Shopify product collections. The quiz now converts at 27% to purchase. Best investment in our website by far.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Valentina Rossi",
        location: "Rome, IT",
        rating: 5,
        title: "Ranu built before/after sliders — customers trust us more now",
        body: "Ranu from ShopifyTasker integrated before/after comparison sliders on our key product pages. It communicates efficacy better than any product description could. It's had a noticeable impact on our conversion rate and customer feedback has been really positive. ShopifyTasker added real value.",
        daysAgo: 12,
        verified: true,
      },
      {
        name: "Lily Zhang",
        location: "Shanghai, CN",
        rating: 5,
        title: "Gaurank built our routine builder — our highest converting page",
        body: "Gaurank from ShopifyTasker built an AM/PM routine builder where customers step through our products and build their skincare routine. It's now our highest converting page on the whole site. That kind of Shopify development goes way beyond a basic setup — it's proper website development.",
        daysAgo: 23,
        verified: true,
      },
      {
        name: "Naomi Osei",
        location: "Accra, GH",
        rating: 5,
        title: "Ayushi from ShopifyTasker built in ingredient transparency",
        body: "Ayushi from ShopifyTasker built a dedicated ingredient breakdown section into every product page. Our customers cite it as a major reason they trust us over competitors. It was a detail I asked for and she delivered it cleanly without making the pages cluttered. Really thoughtful work.",
        daysAgo: 36,
        verified: true,
      },
    ],
  },

  // ─── WEDDING & BRIDAL ──────────────────────────────────────────────────────
  {
    slug: "wedding-bridal",
    aggregateRating: 5.0,
    reviewCount: 33,
    reviews: [
      {
        name: "Charlotte Pemberton",
        location: "London, UK",
        rating: 5,
        title: "Vidi integrated fitting appointments directly into our store",
        body: "Vidi from ShopifyTasker integrated our booking system so brides can book fitting appointments directly from the product page. It sounds simple but it required proper Shopify development to make it seamless. Our in-store appointment rate has increased 40% since the website launched.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Isabella Fontaine",
        location: "Nice, France",
        rating: 5,
        title: "Ranu built our bridal wishlist — word of mouth has increased",
        body: "Ranu from ShopifyTasker built a bridal wishlist and share feature so brides can save gowns and share the list with their bridal party. It's become one of our best word-of-mouth drivers. ShopifyTasker understood the bridal customer journey without us having to explain it.",
        daysAgo: 16,
        verified: true,
      },
      {
        name: "Grace O'Brien",
        location: "Cork, IE",
        rating: 5,
        title: "Gaurank built a store that looks and feels bridal",
        body: "Gaurank from ShopifyTasker did our full Shopify website setup and development. Soft whites, large editorial photography, elegant typography. It communicates the emotion and quality of a bridal boutique before a word is read. Exactly right for our clientele and price point.",
        daysAgo: 27,
        verified: true,
      },
      {
        name: "Sofia Andriessen",
        location: "Amsterdam, NL",
        rating: 5,
        title: "Ayushi handled custom size and fabric options cleanly",
        body: "Wedding gowns come in custom sizes and fabric choices — complex variant setup that most developers get wrong. Ayushi from ShopifyTasker configured it cleanly so brides can specify exactly what they need at checkout. Reduced our admin hugely. Really solid Shopify development.",
        daysAgo: 43,
        verified: true,
      },
    ],
  },

  // ─── COFFEE & TEA ──────────────────────────────────────────────────────────
  {
    slug: "coffee-tea",
    aggregateRating: 4.9,
    reviewCount: 46,
    reviews: [
      {
        name: "Tom Bradley",
        location: "Melbourne, AU",
        rating: 5,
        title: "Vidi built our coffee subscription — 50 subscribers in month one",
        body: "Vidi from ShopifyTasker set up our weekly whole-bean subscription with grind preference, roast selection and delivery day options. All properly developed in Shopify from scratch. We had 50 active subscribers within the first month of launching. ShopifyTasker knows subscriptions.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Hana Nakamura",
        location: "Tokyo, JP",
        rating: 5,
        title: "Ranu added brewing guides — customers love the added value",
        body: "Ranu from ShopifyTasker built brewing guide sections into each product template — French press, pour-over, espresso instructions per coffee. It's a detail that adds real value and customers mention it in reviews. ShopifyTasker thinks about the full website experience, not just the build.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Patrick O'Sullivan",
        location: "Dublin, IE",
        rating: 5,
        title: "Gaurank built origin and tasting notes into our product pages",
        body: "Coffee origin stories, altitude, processing method, tasting notes — all in a clean structured section on each product page. Gaurank from ShopifyTasker built this into the template so it's easy to maintain. It communicates our quality and sourcing values without a long paragraph of text.",
        daysAgo: 22,
        verified: true,
      },
      {
        name: "Nina Svensson",
        location: "Gothenburg, SE",
        rating: 5,
        title: "Ayushi built roast level and flavour filtering — so much easier to browse",
        body: "We have 40+ coffees and customers were getting overwhelmed. Ayushi from ShopifyTasker built filtering by roast level, origin and flavour profile. Customers find exactly what they want in seconds now. The whole Shopify website setup and development was really well handled.",
        daysAgo: 35,
        verified: true,
      },
    ],
  },

  // ─── SPORTS & FITNESS ──────────────────────────────────────────────────────
  {
    slug: "sports-fitness",
    aggregateRating: 4.9,
    reviewCount: 55,
    reviews: [
      {
        name: "Jordan Mitchell",
        location: "Los Angeles, CA",
        rating: 5,
        title: "Vidi built equipment bundles that doubled our AOV",
        body: "Vidi from ShopifyTasker developed full training setup bundles — mat, weights, resistance bands, accessories with bundle pricing. Average order value went up significantly in the first month. That's real Shopify website development that impacts the business, not just a basic store setup.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Lena Fischer",
        location: "Munich, DE",
        rating: 5,
        title: "Ranu handled equipment and supplements on one store cleanly",
        body: "We sell both gym equipment (one-time purchase) and supplements (subscription). Ranu from ShopifyTasker set up both on the same Shopify store without any UX confusion. Customers understand exactly what they're buying. Really thoughtful Shopify website development.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Chris Hammond",
        location: "Auckland, NZ",
        rating: 5,
        title: "Gaurank built sport-specific collections — bounce rate down 25%",
        body: "Gaurank from ShopifyTasker built collections by sport — crossfit, yoga, running, cycling — each with its own landing page. Customers go straight to their sport and find exactly what they need. Our bounce rate improved 25% and time on site has gone up. Proper Shopify development.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Maria Santos",
        location: "Lisbon, PT",
        rating: 5,
        title: "Ayushi set up all our fitness gear variants correctly",
        body: "Dumbbells in 8 weights, resistance bands in 5 levels — Ayushi from ShopifyTasker got all the variant setup done cleanly and fast. Stock management by variant is straightforward now and customers can clearly see what's available. ShopifyTasker made the whole setup easy.",
        daysAgo: 37,
        verified: true,
      },
    ],
  },

  // ─── ART & PRINTS ──────────────────────────────────────────────────────────
  {
    slug: "art-prints",
    aggregateRating: 4.9,
    reviewCount: 31,
    reviews: [
      {
        name: "Sienna Cooper",
        location: "London, UK",
        rating: 5,
        title: "Vidi built print size and framing options that look premium",
        body: "Vidi from ShopifyTasker set up our print size, paper type and framing variant system with clear pricing for each option. The product page looks and feels premium — like you're buying from a real gallery, not just a Shopify store. Excellent Shopify website setup and development.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Felix Weber",
        location: "Vienna, AT",
        rating: 5,
        title: "Ranu built our room mockup visualiser — customers love it",
        body: "Ranu from ShopifyTasker integrated a room mockup visualiser so customers can see how a print looks on their wall. It's the feature customers mention most in our reviews. ShopifyTasker went beyond just building a basic store and thought about what actually converts for an art brand.",
        daysAgo: 15,
        verified: true,
      },
      {
        name: "Amara Obi",
        location: "Nairobi, KE",
        rating: 5,
        title: "Gaurank organised our art catalogue properly",
        body: "Gaurank from ShopifyTasker structured our entire art catalogue — by artist, theme, colour and room. It's easy to browse and easy to find exactly what you want. Before ShopifyTasker, our website was just a wall of prints with no logic to it. Now it actually works as a sales tool.",
        daysAgo: 26,
        verified: true,
      },
      {
        name: "Louisa Park",
        location: "Seoul, KR",
        rating: 5,
        title: "Ayushi built our commission enquiry system into the store",
        body: "We take bespoke commissions alongside selling prints. Ayushi from ShopifyTasker built an enquiry form with fields for brief, size, budget and timeline that feeds into our workflow. No more missed enquiries or messy email threads. Really practical Shopify website development.",
        daysAgo: 41,
        verified: true,
      },
    ],
  },

  // ─── BABY & NURSERY ────────────────────────────────────────────────────────
  {
    slug: "baby-nursery",
    aggregateRating: 5.0,
    reviewCount: 29,
    reviews: [
      {
        name: "Jessica Hart",
        location: "Sydney, AU",
        rating: 5,
        title: "Vidi built in safety certifications — parents trust us immediately",
        body: "Vidi from ShopifyTasker built safety certification badges and compliance information into every product page. Parents notice it immediately and it builds the confidence to purchase. The whole Shopify website setup was done with a real understanding of what baby product buyers look for.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Nina Bergstrom",
        location: "Stockholm, SE",
        rating: 5,
        title: "Ranu set up age-range filtering — parents love it",
        body: "Ranu from ShopifyTasker built age-range filtering — newborn, 3–6 months, 6–12 months — so new parents can find products for their baby's stage immediately. It's the number one thing customers mention when they leave reviews on our store. Small detail, big impact.",
        daysAgo: 16,
        verified: true,
      },
      {
        name: "Amanda Reeves",
        location: "Houston, TX",
        rating: 5,
        title: "Gaurank built nursery bundles — AOV jumped from $120 to $340",
        body: "Gaurank from ShopifyTasker built full nursery setup bundles with accurate pricing and clear product descriptions. Our average order value jumped from $120 to $340 in the first month. That's the impact of proper Shopify website development versus just getting a basic store online.",
        daysAgo: 28,
        verified: true,
      },
      {
        name: "Elise Bouchard",
        location: "Lyon, France",
        rating: 5,
        title: "Ayushi built our baby shower gift registry — new customers keep finding us",
        body: "Ayushi from ShopifyTasker built a baby shower gift registry so expecting parents add items and their guests buy from the list. It's driven a significant amount of new customer acquisition — guests become customers after they discover the store through a registry. Really smart feature.",
        daysAgo: 43,
        verified: true,
      },
    ],
  },

  // ─── HAIR EXTENSIONS ───────────────────────────────────────────────────────
  {
    slug: "hair-extensions",
    aggregateRating: 4.9,
    reviewCount: 58,
    reviews: [
      {
        name: "Danielle Carter",
        location: "Atlanta, GA",
        rating: 5,
        title: "Vidi built our hair match quiz — 31% conversion rate",
        body: "Vidi from ShopifyTasker built a 'find your match' quiz where customers input their natural hair colour and texture and get recommended extension shades and types. The quiz converts at 31% to a purchase. That kind of proper Shopify website development genuinely changes the business.",
        daysAgo: 3,
        verified: true,
      },
      {
        name: "Tia Morrison",
        location: "Birmingham, UK",
        rating: 5,
        title: "Ranu's shade swatch setup cut our returns by 45%",
        body: "Ranu from ShopifyTasker built visual shade swatches with a zoom feature on our product pages. Customers can see the exact colour before buying. Returns dropped 45% after it went live. ShopifyTasker understood exactly what a hair extensions store needs to function well.",
        daysAgo: 11,
        verified: true,
      },
      {
        name: "Aisha Kamara",
        location: "Freetown, SL",
        rating: 5,
        title: "Gaurank built before/after galleries that sell the product for us",
        body: "Gaurank from ShopifyTasker built real customer before/after galleries into our collection and product pages. It pulls our UGC and displays it beautifully. It's honestly the most persuasive content on the whole site. ShopifyTasker thinks about the full website experience.",
        daysAgo: 21,
        verified: true,
      },
      {
        name: "Nadia Mensah",
        location: "Accra, GH",
        rating: 5,
        title: "Ayushi built install bundles — average order value up significantly",
        body: "Ayushi from ShopifyTasker built complete install bundles — weft, closure, frontal, tape-in sets — with accurate pricing and clear descriptions. Average order value increased significantly in the first month. She understood the hair extensions customer without needing everything explained.",
        daysAgo: 34,
        verified: true,
      },
    ],
  },

  // ─── HAIR WIGS ─────────────────────────────────────────────────────────────
  {
    slug: "hair-wigs",
    aggregateRating: 4.9,
    reviewCount: 49,
    reviews: [
      {
        name: "Simone Jackson",
        location: "Chicago, IL",
        rating: 5,
        title: "Vidi set up cap size, density and lace variants correctly",
        body: "Vidi from ShopifyTasker configured cap size, density percentage, lace type and colour — all as clean, working variants on our product pages. Zero customer confusion since it went live. Proper Shopify website development for a wig store is genuinely hard to find. ShopifyTasker nailed it.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Blessing Adeyemi",
        location: "Lagos, NG",
        rating: 5,
        title: "Ranu added wig care guides — customer service questions halved",
        body: "Ranu from ShopifyTasker built dedicated wig care and styling guide pages that link from every product. It reduces customer service questions and adds value post-purchase. Our inbox used to be full of 'how do I care for this' emails. ShopifyTasker made a real difference.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Kezia Williams",
        location: "Luton, UK",
        rating: 5,
        title: "Gaurank integrated virtual try-on — customers spend twice as long on site",
        body: "Gaurank from ShopifyTasker integrated a virtual try-on feature where customers upload a photo to see the wig on themselves. It took a few days to develop and integrate properly. Customers spend twice as long on product pages now and our conversion rate has improved. Well worth it.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Fatima Diallo",
        location: "Dakar, SN",
        rating: 5,
        title: "Ayushi built lace type education into the pages — returns down 35%",
        body: "Ayushi from ShopifyTasker built a lace type education section into our product pages explaining HD lace, transparent lace, 5x5 — with real differences explained clearly. New customers understand what they're buying now. Returns dropped 35%. That's proper Shopify website development.",
        daysAgo: 38,
        verified: true,
      },
    ],
  },

  // ─── CAR ACCESSORIES ───────────────────────────────────────────────────────
  {
    slug: "car-accessories",
    aggregateRating: 4.9,
    reviewCount: 44,
    reviews: [
      {
        name: "Ryan Matthews",
        location: "Houston, TX",
        rating: 5,
        title: "Vidi built year/make/model fitment — customer service queries down 70%",
        body: "Vidi from ShopifyTasker built a fitment filter so customers enter their car and only see compatible accessories. Customer service queries about compatibility dropped 70% overnight. That's the kind of Shopify website development that makes a real operational difference. Brilliant work.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Luke Harrison",
        location: "Melbourne, AU",
        rating: 5,
        title: "Ranu added guaranteed fit badges — conversion rate up 18%",
        body: "Ranu from ShopifyTasker added a 'guaranteed fit for your vehicle' badge that appears once a customer selects their make and model. Such a clean, simple trust element. Our conversion rate on accessory pages is up 18%. ShopifyTasker understands what drives purchases, not just how to build stores.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Carlos Mendoza",
        location: "Mexico City, MX",
        rating: 5,
        title: "Gaurank built interior bundles — AOV from $65 to $120",
        body: "Gaurank from ShopifyTasker built seat cover, steering wheel and floor mat bundle packs with a discount. Average order value went from $65 to $120 after the bundles went live. That's a proper Shopify development result. ShopifyTasker doesn't just build stores, they build revenue.",
        daysAgo: 25,
        verified: true,
      },
      {
        name: "Stefan Kowalczyk",
        location: "Warsaw, PL",
        rating: 5,
        title: "Ayushi delivered 200+ products, tagged and SEO-ready in 5 days",
        body: "Ayushi from ShopifyTasker set up our full store — 200+ products, tagged by vehicle type, properly organised and SEO-optimised — in 5 days. Everything worked on launch day. No issues, no chasing, no revisions needed. ShopifyTasker website setup and development is exactly what it should be.",
        daysAgo: 40,
        verified: true,
      },
    ],
  },

  // ─── B2B WHOLESALE ─────────────────────────────────────────────────────────
  {
    slug: "b2b-wholesale",
    aggregateRating: 4.9,
    reviewCount: 37,
    reviews: [
      {
        name: "David Lin",
        location: "Singapore",
        rating: 5,
        title: "Vidi built proper tiered wholesale pricing using Shopify B2B",
        body: "Vidi from ShopifyTasker built our wholesale pricing tiers — bronze, silver, gold trade accounts — using native Shopify B2B. It's fast, clean and our wholesale team can manage it without any technical help. Proper Shopify website development for a B2B business, not a workaround.",
        daysAgo: 5,
        verified: true,
      },
      {
        name: "Rebecca Taylor",
        location: "Manchester, UK",
        rating: 5,
        title: "Ranu set up MOQs without affecting our retail experience",
        body: "Ranu from ShopifyTasker configured minimum order quantities at product and category level for our wholesale side, with clear messaging. The retail experience is completely unaffected. It's a clean solution that took a couple of days to build properly. Really impressed with ShopifyTasker.",
        daysAgo: 15,
        verified: true,
      },
      {
        name: "Klaus Bauer",
        location: "Frankfurt, DE",
        rating: 5,
        title: "Gaurank handled Net 30 payment terms for our trade customers",
        body: "Gaurank from ShopifyTasker configured Net 30 payment terms for our B2B trade accounts while keeping card-only checkout for retail customers. Exactly what we needed and not something every Shopify developer can set up correctly. ShopifyTasker clearly knows B2B Shopify development.",
        daysAgo: 27,
        verified: true,
      },
      {
        name: "Li Wei",
        location: "Shanghai, CN",
        rating: 5,
        title: "Ayushi built our trade account application — enquiry quality improved",
        body: "Ayushi from ShopifyTasker built a trade account application form that vets wholesale customers before they see our pricing. The quality of our wholesale enquiries improved overnight — we're getting serious buyers, not time-wasters. That's smart Shopify website development.",
        daysAgo: 42,
        verified: true,
      },
    ],
  },

  // ─── FOOD SUPPLY ───────────────────────────────────────────────────────────
  {
    slug: "food-supply",
    aggregateRating: 4.9,
    reviewCount: 40,
    reviews: [
      {
        name: "Ahmed Hassan",
        location: "Dubai, UAE",
        rating: 5,
        title: "Vidi built our B2B portal — wholesale revenue up 55%",
        body: "Vidi from ShopifyTasker built a dedicated trade ordering portal with MOQs, bulk pricing tiers, and a stockist application flow. Our B2B revenue has grown 55% since it went live. ShopifyTasker understands food supply businesses and built exactly what we needed, not a generic solution.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Susan Carpenter",
        location: "Birmingham, UK",
        rating: 5,
        title: "Ranu built allergen and nutritional data into every product",
        body: "Ranu from ShopifyTasker built structured allergen and nutritional information into every product template. It's compliant, it's clear, and it's easy for us to maintain. Food compliance is non-negotiable and ShopifyTasker handled it properly without making the store look clinical.",
        daysAgo: 13,
        verified: true,
      },
      {
        name: "Rafael Costa",
        location: "Porto, PT",
        rating: 5,
        title: "Gaurank set up standing orders — processing time down 60%",
        body: "Gaurank from ShopifyTasker set up recurring standing order scheduling for our restaurant clients — automatic billing, weekly delivery cadence, customer portal. Our order processing time is down 60%. That's the kind of Shopify website development that changes how a business operates.",
        daysAgo: 24,
        verified: true,
      },
      {
        name: "Mei Chen",
        location: "Vancouver, BC",
        rating: 5,
        title: "Ayushi integrated our cold chain carrier correctly",
        body: "Ayushi from ShopifyTasker integrated our cold chain carrier and configured the shipping rules for temperature-controlled products correctly. Not one shipment has gone wrong since launch. Most Shopify developers don't know how to handle this kind of specialist requirement. ShopifyTasker does.",
        daysAgo: 39,
        verified: true,
      },
    ],
  },

  // ─── CANDLE BUSINESS ───────────────────────────────────────────────────────
  {
    slug: "candle-business",
    aggregateRating: 4.9,
    reviewCount: 35,
    reviews: [
      {
        name: "Lucy Pearson",
        location: "Edinburgh, UK",
        rating: 5,
        title: "Vidi built our wedding favour customisation — best performing product",
        body: "Vidi from ShopifyTasker built personalised candle label customisation with MOQs for event orders. Wedding favour candles with custom labels are now our best-selling product line. ShopifyTasker built the feature properly — not a workaround, a proper Shopify website development solution.",
        daysAgo: 4,
        verified: true,
      },
      {
        name: "Céline Aubert",
        location: "Bordeaux, France",
        rating: 5,
        title: "Ranu built scent profiles that sell the sensory experience online",
        body: "Ranu from ShopifyTasker built top, middle and base note descriptions with mood tags and wax type information into our product template. It sells the sensory experience online — something I didn't think was possible. Several customers have said the website made them feel they could smell the candles.",
        daysAgo: 14,
        verified: true,
      },
      {
        name: "Priya Nair",
        location: "London, UK",
        rating: 5,
        title: "Gaurank set up our wholesale channel for boutique stockists",
        body: "Gaurank from ShopifyTasker set up our B2B wholesale channel alongside our D2C store — trade pricing, stockist application form, minimum order logic. It's been live four months and several boutiques have approached us through the trade portal. Really solid Shopify website development.",
        daysAgo: 25,
        verified: true,
      },
      {
        name: "Sarah Muller",
        location: "Zurich, CH",
        rating: 5,
        title: "Ayushi integrated workshop bookings into our Shopify store",
        body: "Ayushi from ShopifyTasker integrated our candle making workshop booking system so customers can book workshops and buy products in the same checkout. It took a few days to develop the integration properly. Our workshop bookings have increased significantly since the new website launched.",
        daysAgo: 40,
        verified: true,
      },
    ],
  },
];

export function getReviews(slug: string): IndustryReviewData | null {
  return reviewsBySlug.find((r) => r.slug === slug) ?? null;
}
